<div class="formheader">
<?php printf($this->title, '"' . $this->key . '"') ?>
</div>
<?php
if (is_array($this->db)):
?>
<a href="<?php echo $this->db['web_site']; ?>"><img
  class="wrapLogo"
  src="<?php echo $this->baseUrl() . $this->db['image']; ?>"
  alt="<?php echo $this->db['database_name']; ?>"
  title="<?php echo $this->db['database_name']; ?>"
/></a>

<table>
    <tr class="even">
        <th class="vertical"><?php echo $this->translate('Full_name'); ?>:</th>
        <td><?php echo $this->db['database_full_name']; ?></td>
    </tr>
    <tr class="odd">
        <th class="vertical"><?php echo $this->translate('Short_name'); ?>:</th>
        <td><?php echo $this->db['database_name']; ?></td>
    </tr>
    <tr class="even">
        <th class="vertical"><?php echo $this->translate('Version'); ?>:</th>
        <td><?php echo $this->db['version']; ?></td>
    </tr>
    <tr class="odd">
        <th class="vertical"><?php echo $this->translate('Release_date'); ?>:</th>
        <td><?php echo $this->db['release_date']; ?></td>
    </tr>
    <tr class="even">
        <th class="vertical"><?php echo $this->translate('Authors_editors'); ?>:</th>
        <td><?php echo $this->db['authors_editors']; ?></td>
    </tr>
    <tr class="odd">
        <th class="vertical"><?php echo $this->translate('Taxonomic_coverage'); ?>:</th>
        <td><?php echo $this->db['taxonomic_coverage']; ?></td>
    </tr>
    <tr class="even">
        <th class="vertical"><?php echo $this->translate('Number_of_species_names'); ?>:</th>
        <td><?php echo $this->db['accepted_species_names']; ?></td>
    </tr>
    <tr class="odd">
        <th class="vertical"><?php echo $this->translate('Number_of_infraspecies_names'); ?>:</th>
        <td><?php echo $this->db['accepted_infraspecies_names']; ?></td>
    </tr>
    <tr class="even">
        <th class="vertical"><?php echo $this->translate('Number_of_common_names'); ?>:</th>
        <td><?php echo $this->db['common_names']; ?></td>
    </tr>
    <tr class="odd">
        <th class="vertical"><?php echo $this->translate('Total_number_of_names'); ?>:</th>
        <td><?php echo $this->db['total_names']; ?></td>
    </tr>
    <tr class="even">
        <th class="vertical"><?php echo $this->translate('Abstract'); ?>:</th>
        <td><?php echo $this->db['abstract']; ?></td>
    </tr>
    <tr class="odd">
        <th class="vertical"><?php echo $this->translate('Organization'); ?>:</th>
        <td><?php echo $this->db['organization']; ?></td>
    </tr>
    <tr class="even">
        <th class="vertical"><?php echo $this->translate('Web_site'); ?>:</th>
        <td><a href="<?php echo $this->db['web_site']; ?>"><?php echo $this->db['web_site']; ?></a></td>
    </tr>
    
</table>
<?php
else:
?>
<p><?php echo $this->translate('Database_not_found'); ?></p>
<?php
endif;
?>