<div class="formheader">
<?php printf($this->title, '"' . $this->key . '"') ?>
</div>
<?php
if (is_array($this->db)):
?>
<a href="<?php echo $this->db['web_site']; ?>"><img
  class="wrapLogo"  
  src="<?php echo $this->baseUrl() . $this->db['image']; ?>"
  alt="<?php echo $this->db['database_name']; ?>"
  title="<?php echo $this->db['database_name']; ?>"
/></a>

<table class="details">
    <tr class="even">
        <th width="200">Full name:</th>
        <td><?php echo $this->db['database_full_name']; ?></td>
    </tr>
    <tr class="odd">
        <th>Short name:</th>
        <td><?php echo $this->db['database_name']; ?></td>
    </tr>
    <tr class="even">
        <th>Version:</th>
        <td><?php echo $this->db['version']; ?></td>
    </tr>
    <tr class="odd">
        <th>Release date:</th>
        <td><?php echo $this->db['release_date']; ?></td>
    </tr>
    <tr class="even">
        <th>Authors/editors:</th>
        <td><?php echo $this->db['authors_editors']; ?></td>
    </tr>
    <tr class="odd">
        <th>Taxonomic coverage:</th>
        <td><?php echo $this->db['database_full_name']; ?></td>
    </tr>
    <tr class="even">
        <th>Number of species names:</th>
        <td><?php echo $this->db['accepted_species_names']; ?></td>
    </tr>
    <tr class="odd">
        <th>Number of infraspecies names:</th>
        <td><?php echo $this->db['accepted_infraspecies_names']; ?></td>
    </tr>
    <tr class="even">
        <th>Number of common names:</th>
        <td><?php echo $this->db['common_names']; ?></td>
    </tr>
    <tr class="odd">
        <th>Total number of names:</th>
        <td><?php echo $this->db['total_names']; ?></td>
    </tr>
    <tr class="even">
        <th>Abstract:</th>
        <td><?php echo $this->db['abstract']; ?></td>
    </tr>
    <tr class="odd">
        <th>Organization:</th>
        <td><?php echo $this->db['organization']; ?></td>
    </tr>
    <tr class="even">
        <th>Web site:</th>
        <td><a href="<?php echo $this->db['web_site']; ?>"><?php echo $this->db['web_site']; ?></a></td>
    </tr>
    
</table>
<?php
else:
?>
<p><?php echo $this->translate('Database_not_found'); ?></p>
<?php
endif;
?>