<div class="form_header">
<?php printf($this->title) ?>
</div>
<?php
if (is_array($this->references)):
?>
<p><?php echo $this->preface; if(count($this->references) > 0) echo ':'; ?></p>
<?php foreach($this->references as $ref): ?>
<?php $rowClass = "odd"; ?>
<table class="details-table">
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th width="150px" class="vertical"><?php echo $this->translate('Author'); ?>:</th>
        <td><?php echo ($ref['author'] == '' ? '&#150;' : $ref['author']); ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Year'); ?>:</th>
        <td><?php echo ($ref['year'] == '' ? '&#150;' : $ref['year']); ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Title'); ?>:</th>
        <td><?php echo ($ref['title'] == '' ? '&#150;' : $ref['title']); ?></td>
    </tr>
<?php if(isset($ref['source'])): ?>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Source'); ?>:</th>
        <td><?php echo ($ref['source'] == '' ? '&#150;' : $ref['source']); ?></td>
    </tr>
<?php endif; ?>
</table>
<?php endforeach;
else:
?>
<p><?php echo $this->translate('No_references_found'); ?></p>
<?php
endif;
?>
<br/>
<div class="results_links">
<a href="javascript:history.back()">
    <?php echo $this->translate('Back_to_last_page'); ?>
</a> |
<a href="<?php echo $this->baseUrl() . '/search/' . $this->latestSearch; ?>">
    <?php echo $this->translate('New_search'); ?>
</a>
</div>