<div class="form_header">
<?php printf($this->title, '"' . $this->key . '"') ?>
</div>
<?php
if ($this->species instanceof ACI_Model_Taxa):
?>
<a href="<?php echo $this->baseUrl() . '/details/database/id/' . $this->species->db_id; ?>"><img
    class="wrapLogo"
    src="<?php echo $this->baseUrl() . $this->species->db_image; ?>"
    alt="<?php echo $this->species->db_name; ?>"
    title="<?php echo $this->species->db_name; ?>"
/></a>
<?php echo $this->species->preface; ?>
<table class="details-table">
<?php if($rowClass = "even")?>
    <tr class="<?php echo $rowClass; ?>">
        <th width="150" class="vertical"><?php echo $this->translate('Accepted_scientific_name'); ?>:</th>
        <td><?php echo $this->species->name; ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Synonym'); ?>:</th>
        <td><?php foreach ($this->species->synonyms as $synonym):
            echo '<span class="taxonomicName">' . $synonym['name'] .
            '</span> ' . $synonym['author'] . ' (' .
            $this->translate($synonym['status']) . ')<br />';
        endforeach;
        ?></td>
    </tr>
<?php if($this->species->infraspecies != null): ?>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Infraspecies'); ?>:</th>
        <td><?php foreach ($this->species->infraspecies as $infraspecies):
            echo '<a href="' . $this->baseUrl() . $infraspecies['url'] . '">' .
            $infraspecies['name'] . '</a><br />';
        endforeach;
        ?></td>
    </tr>
<?php endif; ?>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Common_names'); ?>:</th>
        <td><?php if (is_array($this->species->common_names)): ?>
            <table>
                <tr>
                    <th width="150px"><?php echo $this->translate('Common_name'); ?></th>
                    <th width="150px"><?php echo $this->translate('Language'); ?></th>
                    <th><?php echo $this->translate('Country'); ?></th>
                    <th width="50px"><?php echo $this->translate('Reference'); ?></th>
                </tr>

            <?php foreach ($this->species->common_names as $common): ?>
                <tr>
                    <td><?php echo $common['common_name']; ?></td>
                    <td><?php echo $common['language']; ?></td>
                    <td><?php echo $common['country']; ?></td>
                    <td align="right"><a href="<?php echo $this->baseUrl() .
                          '/references/id/' . $common['reference_id']; ?>"><img
					    src="<?php echo $this->baseUrl() . '/images/book.gif'; ?>"
					    alt="<?php echo $this->translate('Reference'); ?>"
					    title="<?php echo $this->translate('Click_here_to_show_the_literature_reference'); ?>"
                    /></td>
                </tr>
            <?php endforeach; ?>
            </table>
        <?php endif; ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Classification'); ?>:</th>
        <td><?php if (is_array($this->species->common_names)): ?>
            <table>
                <tr>
                    <th width="150px"><?php echo $this->translate('Rank'); ?></th>
                    <th width="150px"><?php echo $this->translate('Taxonomic_Name'); ?></th>
                    <th><?php echo $this->translate('LSID'); ?></th>
                </tr>
        
                <?php foreach ($this->species->hierarchy as $hierarchy): ?>
                <tr>
                    <td><?php echo $hierarchy['taxon']; ?></td>
                    <td><a href="<?php echo $this->baseUrl() . '/browse/tree/id/' .
                      $hierarchy['record_id']; ?>"><?php echo $hierarchy['name']; ?>
                        </a></td>
                    <td class="lsid"><?php echo $hierarchy['LSID']; ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
         <?php endif; ?></td>
     </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Distribution'); ?>:</th>
        <td><?php echo $this->species->distribution; ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Additional_data'); ?>:</th>
        <td><?php echo $this->species->comment . '<br />';
        ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Source_database'); ?>:</th>
        <td><a href="<?php echo $this->baseUrl() . '/details/database/id/' . $this->species->db_id; ?>"><?php
          echo $this->species->db_name . '</a>, ' . $this->species->db_version;
        ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Latest_taxonomic_scrutiny'); ?>:</th>
        <td><?php echo $this->species->specialist_name;
            if($this->species->specialist_name != ""):
                echo ', ';
            endif;
            echo $this->species->scrutiny_date;
        ?></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Online_resource'); ?>:</th>
        <td><a href="<?php echo $this->species->web_site; ?>"><?php
          echo $this->species->web_site; ?></a></td>
    </tr>
<?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('CoL_taxon_LSID'); ?>:</th>
        <td><p class="lsid"><?php echo $this->species->lsid;
        ?></p></td>
    </tr>
</table>
        <?php
else:
?>
<p><?php echo $this->translate('Species_not_found'); ?></p>
<?php
endif;
?>
<div class="results_links">
<a href="javascript:history.back()">
    <?php echo $this->translate('Back_to_last_page'); ?>
</a> |
<a href="<?php echo $this->baseUrl() . '/search/' . $this->search . '/key/'
    . $this->key . '/submit/0'; ?>"><?php echo $this->translate('New_search'); ?>
</a>
</div>