<?php
/**
 * Annual Checklist Interface
 *
 * webservices/index.phtml
 * Webservices documentation
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<html>
<title>Catalogue of Life Annual Checklist Web Service Help</title>
<body>
<style>
<!--
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
    {mso-style-parent:"";
    margin:0cm;
    margin-bottom:.0001pt;
    mso-pagination:widow-orphan;
    font-size:12.0pt;
    font-family:"Times New Roman";
    mso-fareast-font-family:"Times New Roman";
    mso-ansi-language:EN-US;
    mso-fareast-language:EN-US;}
@page Section1
    {size:612.0pt 792.0pt;
    margin:72.0pt 90.0pt 72.0pt 90.0pt;
    mso-header-margin:36.0pt;
    mso-footer-margin:36.0pt;
    mso-paper-source:0;
    mso-gutter-direction:rtl;}
div.Section1
    {page:Section1;}
-->
</style><!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
    {mso-style-name:"Table Normal";
    mso-tstyle-rowband-size:0;
    mso-tstyle-colband-size:0;
    mso-style-noshow:yes;
    mso-style-parent:"";
    mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
    mso-para-margin:0cm;
    mso-para-margin-bottom:.0001pt;
    mso-pagination:widow-orphan;
    font-size:10.0pt;
    font-family:"Times New Roman";
    mso-fareast-font-family:"Times New Roman";
    mso-ansi-language:#0400;
    mso-fareast-language:#0400;
    mso-bidi-language:#0400;}
</style>
<![endif]-->
<!--StartFragment-->
<div
 style="border-style: solid none none; border-color: windowtext -moz-use-text-color -moz-use-text-color; border-width: 1pt medium medium; padding: 10pt 0cm 0cm;">
<p class="MsoNormal" style="border: medium none ; padding: 0cm;"><b><span
 style="font-family: Arial; color: maroon;">Table of Contents - <?php echo $this->edition; ?> Annual Checklist Web Service v<?php echo $this->version; ?></span></b><span
 style="font-size: 10pt; font-family: Arial; color: maroon;"
><o:p></o:p></span></p>
</div>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">1. URL<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>1.1
Parameters<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>1.2
Example URLs<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">2. XML format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>2.1
Basic format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.1.1 Terse
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.1.2 Full
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>2.2
Accepted
species and infraspecific names<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.2.1 Terse
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.2.2 Full
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>2.3
Species or infraspecific synonyms<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.3.1 Terse
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.3.2 Full
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>2.4
Common names for
species or infraspecific taxa<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.4.1 Terse
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.4.2 Full
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>2.5
Higher taxa<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.5.1 Terse
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>2.5.2 Full
format<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>

<div
 style="border-style: solid none none; border-color: windowtext -moz-use-text-color -moz-use-text-color; border-width: 1pt medium medium; padding: 10pt 0cm 0cm;">
<p class="MsoNormal" style="border: medium none ; padding: 0cm;"><b><span
 style="font-family: Arial; color: maroon;">URL</span></b><span
 style="font-size: 10pt; font-family: Arial; color: maroon;"
><o:p></o:p></span></p>
</div>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">The
Web service (version <?php echo $this->version; ?>) is currently available at:<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
 <a href="<?php echo $this->location; ?>"><?php echo $this->location; ?></a></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 11pt; font-family: Arial;">Parameters</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">There
is one required parameter, which is either <b>name</b> or <b>id</b>.
Give <i>either

</i>a name or an ID. If an ID is given, the name parameter may not be
used, and
vice versa.<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">The
parameters <b>format</b>, <b>response</b> and <b>start</b> are all
optional.<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal"
 style="margin: 2pt 0cm 2pt 63.8pt; text-indent: -63.8pt;"><b><span
 style="font-size: 10pt; font-family: Arial;">name</span></b><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>The string to search for. Only exact matches found the name given will be
returned, unless a wildcard (*) is appended. Wildcards are allowed only at the end of the string. This offers the
option to e.g. search for genus* to retrieve the genus plus all its (infra)species.
The name must be at least 3 characters long, not counting the wildcard character.<o:p></o:p></span></p>

<p class="MsoNormal"
 style="margin: 2pt 0cm 2pt 63.8pt; text-indent: -63.8pt;"><b><span
 style="font-size: 10pt; font-family: Arial;">id</span></b><span
 style="font-size: 10pt; font-family: Arial;"> <span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>The
record ID of the specific record to return (only for scientific names
of species or infraspecific taxa)<o:p></o:p></span></p>
<p class="MsoNormal"
 style="margin: 2pt 0cm 2pt 63.8pt; text-indent: -63.8pt;"><b><span
 style="font-size: 10pt; font-family: Arial;">format</span></b><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>format
of
the results returned. Valid values are format=xml and format=php; if
the format
parameter is omitted, the results are returned in the default XML
format. If
format=php then results are returned as a PHP array in serialized
string
format, which can be converted back to an array in PHP using the
unserialize
command<o:p></o:p></span></p>
<p class="MsoNormal"
 style="margin: 2pt 0cm 2pt 63.8pt; text-indent: -63.8pt;"><b><span
 style="font-size: 10pt; font-family: Arial;">response</span></b><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>Type of response
returned. Valid values are response=terse and response=full. if the
response
parameter is omitted, the results are returned in the default terse
format. If
format=terse then a minimum set of results are returned (this is faster
and
smaller, enough for name lookup), if format=full then all available
information
is returned<o:p></o:p></span></p>
<p class="MsoNormal"
 style="margin: 2pt 0cm 2pt 63.8pt; text-indent: -63.8pt;"><b><span
 style="font-size: 10pt; font-family: Arial;">start</span></b><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>The
first record to return. If omitted, the results are returned from the
first
record (start=0). This is useful if the total number of results is
larger than
the maximum number of results returned by a single Web service query
(currently
the maximum number of results returned by a single query is 500 for
terse
queries and 50 for full queries).<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 11pt; font-family: Arial;">Example URLs</span></b><b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></b></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
 <a href="<?php echo $this->location; ?>?name=Tara+spinosa">
 <?php echo $this->location; ?>?name=Tara+spinosa
 </a><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
 <a href="<?php echo $this->location; ?>?name=Apus">
 <?php echo $this->location; ?>?name=Apus
 </a><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
 <a href="<?php echo $this->location; ?>?id=7264597">
 <?php echo $this->location; ?>?id=7a037a890e7f86e56c33ec78343eb842</a>
 <o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
 <a href="<?php echo $this->location; ?>?name=Platalea+leucorodia">
 <?php echo $this->location; ?>?name=Platalea+leucorodia
 </a><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
 <a href="<?php echo $this->location; ?>?id=7a037a890e7f86e56c33ec78343eb842&format=php&response=full">
 <?php echo $this->location; ?>?id=7a037a890e7f86e56c33ec78343eb842&amp;format=php&amp;response=full
 </a><o:p></o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></b></p>

<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></b></p>
<div
 style="border-style: solid none none; border-color: windowtext -moz-use-text-color -moz-use-text-color; border-width: 1pt medium medium; padding: 10pt 0cm 0cm;">
<p class="MsoNormal" style="border: medium none ; padding: 0cm;"><b><span
 style="font-family: Arial; color: maroon;">XML format</span></b><b><span
 style="font-size: 10pt; font-family: Arial; color: maroon;"
><o:p></o:p></span></b></p>
</div>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></b></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 11pt; font-family: Arial;">Basic format</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">The
search parameters and error message returned by the Web service are
included as
parameters of the &lt;results&gt; tag.<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;results
id="" name="" total_number_of_results=""
number_of_results="" start=""
error_message="" version="<?php echo $this->version; ?>"&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;result&gt;&lt;/result&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;result /&gt; for each record returned --&gt;</span><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/results&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">Each
result can be an accepted (infra)species name, an (infra)species
synonym, a
common name for an (infra)species, or a higher taxon.<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 11pt; font-family: Arial;">Accepted
(infra)species name</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Terse
response</span></b><span style="font-size: 10pt; font-family: Arial;"
><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Full response</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;<span
 style="">&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;infraspecies&gt;&lt;/infraspecies&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;additional_comments&gt;&lt;/additional_comments&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;distribution&gt;&lt;/distribution&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;record_scrutiny_date&gt;&lt;/record_scrutiny_date&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for each higher taxon --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/taxon&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;child_taxa&gt;
<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;&lt;!-- only for species --&gt;</span><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for each child taxon --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;/taxon&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/child_taxa&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;synonyms&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;synonym&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;synonym /&gt; for each taxon --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;</p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;additional_data&gt;&lt;/additional_data&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;record_scrutiny_date&gt;&lt;/record_scrutiny_date&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
<span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/synonym&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/synonyms&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;common_names&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;common_name&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;common_name /&gt; for each name --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;country&gt;&lt;/country&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;language&gt;&lt;/language&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/common_name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/common_names&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 11pt; font-family: Arial;">(Infra)species
synonym</span></b><span style="font-size: 10pt; font-family: Arial;"
><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Terse
response</span></b><span style="font-size: 10pt; font-family: Arial;"
><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;accepted
name&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- duplicates the terse response for an accepted name --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/accepted
name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Full response</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;infraspecies&gt;&lt;/infraspecies&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;additional_comments&gt;&lt;/additional_comments&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;distribution&gt;&lt;/distribution&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;record_scrutiny_date&gt;&lt;/record_scrutiny_date&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;accepted_name&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- duplicates the full response for an accepted name --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;additional_comments&gt;&lt;/additional_comments&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;distribution&gt;&lt;/distribution&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">
 <span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for each higher taxon --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/taxon&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;child_taxa&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for each child taxon --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/taxon&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/child_taxa&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;synonyms&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;synonym&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;synonym /&gt; for each taxon --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;</p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;additional_data&gt;&lt;/additional_data&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;record_scrutiny_date&gt;&lt;/record_scrutiny_date&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/synonym&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span></span><span style="font-size: 10pt; font-family: Arial;"
>&lt;/synonyms&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;common_names&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;common_name&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;common_name /&gt; for each name --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;country&gt;&lt;/country&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;language&gt;&lt;/language&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/common_name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/common_names&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/accepted
name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 11pt; font-family: Arial;">Common name
for (infra)species</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Terse
response</span></b><span style="font-size: 10pt; font-family: Arial;"
><o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;language&gt;&lt;/language&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;country&gt;&lt;/country&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;accepted
name&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- duplicates the terse response for an accepted name --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/accepted
name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Full response</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;language&gt;&lt;/language&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;country&gt;&lt;/country&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;references&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;accepted_name&gt;
<span style="color: #666">
&nbsp;&nbsp;&nbsp;&nbsp;&lt;!-- duplicates the full response for an accepted name --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;additional_comments&gt;&lt;/additional_comments&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;distribution&gt;&lt;/distribution&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for higher taxon --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/taxon&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;child_taxa&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for each child taxon --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/taxon&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/child_taxa&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;synonyms&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;synonym&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;synonym /&gt; for each taxon --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;</p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;additional_data&gt;&lt;/additional_data&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;online_resource&gt;&lt;/online_resource&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database&gt;&lt;/source_database&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source_database_url&gt;&lt;/source_database_url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;record_scrutiny_date&gt;&lt;/record_scrutiny_date&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/reference&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/synonym&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/synonyms&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;common_names&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;common_name&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;common_name /&gt; for each name --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;country&gt;&lt;/country&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;language&gt;&lt;/language&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;reference&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;reference /&gt; for each reference --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;year&gt;&lt;/year&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;title&gt;&lt;/title&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;source&gt;&lt;/source&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;/reference&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/references&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/common_name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/common_names&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/accepted
name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 11pt; font-family: Arial;">Higher taxa</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Terse
response</span></b><span style="font-size: 10pt; font-family: Arial;"
><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style=""><b><span
 style="font-size: 10pt; font-family: Arial;">Full response</span></b><span
 style="font-size: 10pt; font-family: Arial;"><o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_status&gt;&lt;/name_status&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for each higher taxon --&gt;</span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;rank&gt;&lt;/rank&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/taxon&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;">&lt;/classification&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">
</span>&lt;child_taxa&gt;</p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;taxon&gt;<span style="color: #666">&nbsp;&nbsp;&nbsp;&nbsp;
&lt;!-- one &lt;taxon /&gt; for each child taxon --&gt;</span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;id&gt;&lt;/id&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name&gt;&lt;/name&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;name_html&gt;&lt;/name_html&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;genus&gt;&lt;/genus&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</span>&lt;species&gt;&lt;/species&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies_marker&gt;&lt;/infraspecies_marker&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;infraspecies&gt;&lt;/infraspecies&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;author&gt;&lt;/author&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;url&gt;&lt;/url&gt;<o:p></o:p></span></p>

<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">&nbsp;&nbsp;&nbsp;&nbsp;
</span>&lt;/taxon&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><span
 style="">
</span>&lt;/child_taxa&gt;<o:p></o:p></span></p>
<p class="MsoNormal" style=""><span
 style="font-size: 10pt; font-family: Arial;"><o:p>&nbsp;</o:p></span></p>

<!--EndFragment-->
</body>
</html>