<?php
/**
 * Annual Checklist Interface
 *
 * headers.phtml
 * Export template for search distribution headers
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<?php
echo $this->translate('Distribution') . $this->separator .
     $this->translate('Name') . $this->separator .
     $this->translate('Group') . $this->separator .
     $this->translate('Source_database') . PHP_EOL;