<?php
echo $this->translate('Common_name') . $this->separator .
     $this->translate('Accepted_scientific_name') . $this->separator .
     $this->translate('Group') . $this->separator .
     $this->translate('Database') . PHP_EOL;
foreach($this->data as $k => $data) {
    echo $data['name'] . $this->separator .
         $data['accepted_species_name'] . $this->separator .
         $data['kingdom'] . $this->separator .
         $data['db_name'] . PHP_EOL;
         unset($this->data[$k]);
}