<?php
echo $this->translate('Distribution') . $this->tab .
     $this->translate('Name') . $this->tab .
     $this->translate('Group') . $this->tab .
     $this->translate('Database') . PHP_EOL;
foreach($this->data as $k => $data) {
    echo $data['distribution'] . $this->tab .
         $data['name'] . $this->tab .
         $data['kingdom'] . $this->tab .
         $data['db_name'] . PHP_EOL;
         unset($this->data[$k]);
}