
<div class="page_header">
<?php echo "Literature references in BHL-Europe: {$this->bhl->numFound} found (unvetted)"; ?>
</div>


<?php
	$rowClass = 'odd';
	foreach($this->bhl->references as $reference) {
		$url = sprintf($this->portalUrlPattern, $reference->pid);
		$imgUrl = null;
		$id = substr($reference->pid, (strpos($reference->pid, '-')+1));
		if($id) {
			$imgUrl = sprintf($this->imageUrlPattern, $id);
			// make sure image exists
			$h = fopen($imgUrl, 'r');
			if(!$h) {
				$imgUrl = null;
			}
			else {
				fclose($h);
			}
		}
?>

<?php if($imgUrl !== null) { ?>
<div style="position:relative;padding:0;">
<?php } ?>

<table class="details-table">

<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical" style="width:20%;"><?php echo $this->translate('Author'); ?>:</th>
        <td><?php echo $reference->author; ?></td>
    </tr>
    
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Title'); ?>:</th>
        <td><?php echo $reference->title; ?></td>
    </tr>
        
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Year'); ?>:</th>
        <td><?php echo $reference->year; ?></td>
    </tr>
    
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Publisher'); ?>:</th>
        <td><?php echo $reference->publisher; ?></td>
    </tr>
            
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('URL'); ?>:</th>
        <td><a href="<?php echo $url; ?>" target="_new"><?php echo $url; ?></a></td>
    </tr>

</table>

<?php if($imgUrl !== null) { ?>
<img src="<?php echo $imgUrl; ?>" style="position:absolute;right:20px;top:20px;opacity:0.6;height:80px;border:1px solid #000;" />
</div>
<?php } ?>


<?php
	}
?>




<div class="page_links">
<a href="javascript:history.back()">
    <?php echo $this->translate('Back_to_last_page'); ?>
</a> |
<a href="<?php echo $this->baseUrl() . '/' . $this->latestSearch; ?>">
    <?php echo $this->translate('New_search'); ?>
</a>
</div>