
<div class="page_header">
<?php echo "Literature references in BHL-Europe: {$this->bhl->numFound} found (unvetted)"; ?>
</div>


<?php
	$rowClass = 'odd';
	foreach($this->bhl->references as $reference) {
		$url = sprintf($this->portalUrlPattern, $reference->pid);
			
?>

<table class="details-table">

<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical" style="width:20%;"><?php echo $this->translate('Author'); ?>:</th>
        <td><?php echo $reference->author; ?></td>
    </tr>
    
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Title'); ?>:</th>
        <td><?php echo $reference->title; ?></td>
    </tr>
        
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Year'); ?>:</th>
        <td><?php echo $reference->year; ?></td>
    </tr>
    
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Publisher'); ?>:</th>
        <td><?php echo $reference->publisher; ?></td>
    </tr>
            
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('URL'); ?>:</th>
        <td><a href="<?php echo $url; ?>" target="_new"><?php echo $url; ?></a></td>
    </tr>

</table>

<?php
	}
?>




<div class="page_links">
<a href="javascript:history.back()">
    <?php echo $this->translate('Back_to_last_page'); ?>
</a> |
<a href="<?php echo $this->baseUrl() . '/' . $this->latestSearch; ?>">
    <?php echo $this->translate('New_search'); ?>
</a>
</div>