<? $this->doctype();?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->escape($this->pageTitle); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()."/styles/style.css"; ?>" />

    <script language="JavaScript" src="<?php echo $this->baseUrl()."/".$this->scriptFolder."menu.js"; ?>"></script>

</head>
<body>
    <div id="header">
        <img src="<?php echo $this->imageFolder; ?>banner.gif" />
    </div>
    <div id="menu" class="view">
		<ul id="nav">
		  <li<?php if($menuItem == "browse") echo " class=\"menuselected\""; ?>><a href="<?php echo $this->baseUrl(); ?>/browse/tree"><img src="<?php echo $this->imageFolder; ?>icon_mini_folder.gif" />
		    Browse</a>
		    <ul>
		      <li><a href="<?php echo $this->baseUrl(); ?>/browse/tree">Taxonomic tree</a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/browse/classification">Taxonomic classification</a></li>
		    </ul>
		  </li>
		  <li><a href="<?php echo $this->baseUrl(); ?>/search/all"><img src="<?php echo $this->imageFolder; ?>icon_mini_search.gif" />
		    Search</a>
		    <ul>
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/all">Search all names</a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/scientific">Search for scientific names</a></li> 
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/common">Search for common names</a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/distribution">Search by distribution</a></li> 
		    </ul>
		  </li>
		  <li><a href="<?php echo $this->baseUrl(); ?>/info/about"><img src="<?php echo $this->imageFolder; ?>icon_mini_faq.gif" />
		    Info</a>
		    <ul>
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/about">About the Catalogue of Life</a></li> 
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/anual_checklist">The 2009 Annual Checklist</a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/source_databases">Source databases</a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/management_hierarcht">Towards Management Hierarchy</a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/coptright">Copyright, reproduction & sale</a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/cite">How to cite this work</a></li>
              <li><a href="<?php echo $this->baseUrl(); ?>/info/websites">Web sites</a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/contact">Contact us</a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/acknowledgements">Acknowledgements</a></li> 
		    </ul>
		  </li>
		</ul>
    </div>
    <div id="content" class="view">
        <p class="formheader"><?php echo $this->layout()->title; ?></p>
        <div class="divider"></div>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>