<? $this->doctype();?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->escape($this->pageTitle); ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()."/styles/style.css"; ?>" />

    <script language="JavaScript" src="<?php echo $this->baseUrl()."/".$this->scriptFolder."menu.js"; ?>"></script>

</head>
<body>
    <div id="header">
        <img src="<?php echo $this->imageFolder; ?>banner.gif" />
    </div>
    <div id="menu" class="view">
		<ul id="nav">
		  <li<?php if($menuItem == "browse") echo " class=\"menuselected\""; ?>><a href="<?php echo $this->baseUrl(); ?>/browse/tree"><img src="<?php echo $this->imageFolder; ?>icon_mini_folder.gif" />
		    <?php echo $this->translate('Browse'); ?></a>
		    <ul>
		      <li><a href="<?php echo $this->baseUrl(); ?>/browse/tree"><?php echo $this->translate('Taxonomic_tree'); ?></a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/browse/classification"><?php echo $this->translate('Taxonomic_classification'); ?></a></li>
		    </ul>
		  </li>
		  <li><a href="<?php echo $this->baseUrl(); ?>/search/all"><img src="<?php echo $this->imageFolder; ?>icon_mini_search.gif" />
		    <?php echo $this->translate('Search'); ?></a>
		    <ul>
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/all"><?php echo $this->translate('Search_all_Names'); ?></a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/scientific"><?php echo $this->translate('Search_scientific_names'); ?></a></li> 
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/common"><?php echo $this->translate('Search_common_names'); ?></a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/search/distribution"><?php echo $this->translate('Search_distribution'); ?></a></li> 
		    </ul>
		  </li>
		  <li><a href="<?php echo $this->baseUrl(); ?>/info/about"><img src="<?php echo $this->imageFolder; ?>icon_mini_faq.gif" />
		    <?php echo $this->translate('Info'); ?></a>
		    <ul>
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/about"><?php echo $this->translate('Info_About'); ?></a></li> 
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/anual_checklist"><?php echo $this->translate('Info_Annual_Checklist'); ?></a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/source_databases"><?php echo $this->translate('Source_databases'); ?></a></li>
		      <li><a href="<?php echo $this->baseUrl(); ?>/info/management_hierarcht"><?php echo $this->translate('Management_Hierarchy'); ?></a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/coptright"><?php echo $this->translate('Copyright_reproduction_sale'); ?></a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/cite"><?php echo $this->translate('Cite_work'); ?></a></li>
              <li><a href="<?php echo $this->baseUrl(); ?>/info/websites"><?php echo $this->translate('Web_sites'); ?>Web sites</a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/contact"><?php echo $this->translate('Contact_us'); ?>Contact us</a></li> 
              <li><a href="<?php echo $this->baseUrl(); ?>/info/acknowledgements"><?php echo $this->translate('Acknowledgements'); ?>Acknowledgements</a></li> 
		    </ul>
		  </li>
		</ul>
    </div>
    <div id="content" class="view">
        <p class="formheader"><?php echo $this->layout()->title; ?></p>
        <div class="divider"></div>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>