<?php
/**
 * Annual Checklist Interface
 *
 * ac.phtml
 * Info - Annual Checklist page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Info_annual_checklist'), $this->app->edition);
?>
</div>
<?php
echo $this->navigator_top;
$fcImgAlt = $this->app->edition . ' Annual Checklist DVD front cover';
?>
<div class="info_content">
<p style="margin-bottom: 20px;">

<span style="width: 325px; float: right; padding-left: 5px; margin-left: 5px; margin-bottom: 15px;"><img
    src="../images/dvd_front_cover.png"
    title="2012 Annual Checklist DVD front cover"
    alt="2011 Annual Checklist DVD front cover" width="317"
    height="317" class="bordered-img" /><br />
<span style="font-size: 10px; font-style: italic; ">In memory of <b>Professor Frank Bisby</b> (24/04/1945 &#8212; 25/10/2011), founder and champion of Catalogue of Life. Frank was a leader in the global communication of taxonomy and biodiversity informatics and a passionate advocate for his science.  He had a profound impact on this international effort to catalogue the world's species and he will be forever honoured and remembered by his colleagues.</span>
</span>

<i><b>2012 Annual Checklist</b></i> contains contributions from 115 databases with information on <?php echo $this->stats['species']; ?>  species, <?php echo $this->stats['infraspecific_taxa']; ?> infraspecific taxa and also includes <?php echo $this->stats['synonyms']; ?> synonyms and <?php echo $this->stats['common_names']; ?> common names covering the following groups <i>(all statistical figures in the booklet are based on the interface version 1.6 and might have minor deviations from figures displayed in the interface version 1.8)</i>:
 <!-- <?php #echo $this->stats['databases']; ?><b>113</b> 
databases with information on <b><?php echo $this->stats['species']; ?> </b>
species and <b><?php echo $this->stats['infraspecific_taxa']; ?> </b> infraspecific
taxa, and also includes <b><?php echo $this->stats['synonyms']; ?></b> synonyms
and <b><?php echo $this->stats['common_names']; ?></b> common names covering the
following groups:</p> -->
<p><b class="field_header">Viruses</b>
 &#8226; <?php
echo $this->internalLink('Viruses and Subviral agents from [link:db:14]');
?>
</p>
<p><b class="field_header">Bacteria</b> and <b class="field_header">Archaea</b> from
<?php echo $this->internalLink('[link:db:4]'); ?>
 &#8226; <?php echo $this->internalLink('Blue-green algae (Cyanobacteria) from [link:db:2]'); ?>
</p>
<p><b class="field_header">Chromista</b>
 &#8226; <?php echo $this->internalLink('Chromistan fungi from [link:db:28]'); ?>
 &#8226; <?php echo $this->internalLink('Chromistan algae from [link:db:2]'); ?>
</p>
<p><b class="field_header">Protozoa</b>
 &#8226; <?php echo $this->internalLink('Major groups from [link:db:17] and [link:db:2]'); ?>,
 &#8226; <?php echo $this->internalLink('Ciliates from [link:db:113]'); ?>,
 &#8226; <?php echo $this->internalLink('Polycystines from [link:db:109]'); ?>,
 &#8226; <?php echo $this->internalLink('Protozoan fungi from [link:db:28] and [link:db:33] database'); ?>
 &#8226; <?php echo $this->internalLink('Slime moulds from [link:db:53]'); ?>
</p>
<p><b class="field_header">Fungi</b>
 &#8226; <?php echo $this->internalLink('Various taxa in whole or in part from CABI Bioservices databases ([link:db:28], [link:db:23], [link:db:25], [link:db:97] and [link:db:38] databases) and from three other databases covering [link:db:36], [link:db:12], [link:db:33], [link:db:98] Lichens from [link:db:79]'); ?>
</p>
<p><b class="field_header">Plantae (Plants)</b>
 &#8226; <?php echo $this->internalLink('Mosses from [link:db:19]'); ?>
 &#8226; <?php echo $this->internalLink('Liverworts and hornworts from [link:db:74]'); ?>
 &#8226; <?php echo $this->internalLink('Conifers from [link:db:45]'); ?>
 &#8226; <?php echo $this->internalLink('Cycads and 6 flowering plant families from [link:db:16] and 99 families from [link:db:24]'); ?>
 &#8226; <?php echo $this->internalLink('Plus individual flowering plants families from [link:db:40], [link:db:73], [link:db:117], [link:db:66], [link:db:116], [link:db:72], [link:db:15], [link:db:43], [link:db:56], [link:db:102], [link:db:48], [link:db:64], [link:db:114]'); ?>.</p>
<p><b class="field_header">Animalia (Animals)</b>
 &#8226; <?php echo $this->internalLink('Marine groups from WoRMS (including 7 New! checklists), [link:db:35], ITIS, [link:db:13], [link:db:9]'); ?>
 &#8226; <?php echo $this->internalLink('Rotifers from [link:db:47] database'); ?>
 &#8226; <?php echo $this->internalLink('Entoprocts, water bears from ITIS'); ?>
 &#8226; <?php echo $this->internalLink('Freshwater crabs from [link:db:77]'); ?>
 &#8226; <?php echo $this->internalLink('Spiders, scorpions, ticks &amp; mites from [link:db:29], [link:db:71] , ITIS, [link:db:30], Mites GSDs, [link:db:82] &amp;  [link:db:80]'); ?>
 &#8226; <?php echo $this->internalLink('Diplopods, centipedes, pauropods and symphylans from [link:db:41] and [link:db:42]'); ?>
 &#8226; <?php echo $this->internalLink('Dragonflies and damselflies from [link:db:20] database'); ?>
 &#8226; <?php echo $this->internalLink('Stoneflies from [link:db:65]'); ?>
 &#8226; <?php echo $this->internalLink('Cockroaches from [link:db:51]'); ?>
 &#8226; <?php echo $this->internalLink('Praying mantids from [link:db:62]'); ?>
 &#8226; <?php echo $this->internalLink('Stick and leaf insects from [link:db:50] '); ?>
 &#8226; <?php echo $this->internalLink('Grasshoppers, locusts, katydids and crickets from [link:db:21] '); ?>
 &#8226; <?php echo $this->internalLink('Webspinners from [link:db:89] '); ?>
 &#8226; <?php echo $this->internalLink('Some groups of true bugs from [link:db:26], [link:db:11], [link:db:52], [link:db:54], [link:db:61] , [link:db:76], [link:db:83], [link:db:84] &amp; [link:db:96]'); ?>
&#8226; <?php echo $this->internalLink('Twisted-wing parasites from [link:db:103] '); ?>
&#8226; <?php echo $this->internalLink('Lacewings, antlions, owlflies, fishflies, dobsonflies & snakeflies from [link:db:55]'); ?>
 &#8226; <?php echo $this->internalLink('Some beetle groups from the [link:db:27], [link:db:32], [link:db:39]  &amp; ITIS'); ?>
 &#8226; <?php echo $this->internalLink('Fleas from [link:db:22]'); ?>
 &#8226; <?php echo $this->internalLink('Flies, mosquitoes, bots, midges and gnats from [link:db:101], [link:db:5] & [link:db:6]'); ?>
 &#8226; <?php echo $this->internalLink('Butterflies and moths from [link:db:18], [link:db:46], [link:db:31], [link:db:49]'); ?>
 &#8226; <?php echo $this->internalLink('Bees &amp; wasps from ITIS, [link:db:68], [link:db:34] and [link:db:37]'); ?>
 &#8226; <?php echo $this->internalLink('Snails and slugs from [link:db:1]'); ?>
 &#8226; <?php echo $this->internalLink('Fishes from [link:db:10]'); ?>
 &#8226; <?php echo $this->internalLink('Reptiles from [link:db:8]'); ?>
 &#8226; <?php echo $this->internalLink('Amphibians, birds and mammals from ITIS'); ?>
</p>
<p><span class="field_header">PLUS</span> additional species of many groups from
<?php echo $this->internalLink('[link:db:17] & [link:db:75]'); ?>
</p>
<br />
<p class="field_header">The Catalogue of Life Editors</p>
<p>The Catalogue of Life programme combines the outputs of the Species
2000 programme (led by Frank Bisby † from Reading, UK) and the ITIS
programme (led by Thomas Orrell from Washington, USA). Assembly and
publication of the Annual Checklist is managed by Yuri Roskov in Reading
working with colleagues around the world.</p>
<p>&#8226; <b><em>Frank Bisby</em></b> †, Species 2000 Executive Secretary (until November 2011) at the CoL Secretariat, University of Reading, UK</p>
<p>&#8226; <b><em>Yuri Roskov</em></b>, Catalogue of Life Executive Editor at the CoL Secretariat, University of Reading, UK</p>
<p>&#8226; <b><em>Alastair Culham</em></b>, PI for i4Life and 4D4Life (from December 2011) EC projects at the CoL Secretariat, University of Reading, UK.</p>
<p>&#8226; <b><em>Thomas Orrell</em></b>, ITIS Acting Director, ITIS Secretariat, Smithsonian Institution, Washington DC, USA</p>
<p>&#8226; <b><em>David Nicolson</em></b>, ITIS Data Development Leader, USGS/Smithsonian Institution, Washington DC, USA</p>
<p>&#8226; <b><em>Luvie Paglinawan</em></b>, Catalogue of Life Database Manager, at the CoL Philippines Office, FIN, Los Ba&ntilde;os, Philippines</p>
<p>&#8226; <b><em>Nicolas Bailly</em></b>, Taxonomic Editorial Advisor for Marine sectors and CoL Philippines Office, FIN, Los Ba&ntilde;os, Philippines</p>
<p>&#8226; <b><em>Ward Appeltans</em></b>, WoRMS database Manager, VLIZ, Oostende, Belgium</p>
<p>&#8226; <b><em>Paul Kirk</em></b>, Taxonomic Editorial Advisor for Fungi and Chromista sectors at CABI, Egham, UK</p>
<p>&#8226; <b><em>Thierry Bourgoin</em></b>, Taxonomic Editorial Advisor for Insects at the Museum National d'Histoire Naturelle, Paris, France</p>
<p>&#8226; <b><em>Guy Baillargeon</em></b>, Taxonomic Editorial Advisor for Plants at Agriculture and Agri-Food Canada</p>
<p>&#8226; <b><em>David Ouvrard</em></b>, 4D4Life GSD network convener at the Museum National d'Histoire Naturelle, Paris, France</p>
<br/>
<p class="field_header">The Catalogue of Life Assembly Team</p>
<p>&#8226; <b><em>Luvie Paglinawan</em></b>, Catalogue of Life Database Manager and <b><em>Luisa Abucay</em></b>, Assistant for CoL Database Manager, at the CoL Philippines Office, FIN, Los Ba&ntilde;os, Philippines.</p>
<p>&#8226; <b><em>Viktoras Did&#382;iulis</em></b>, Production Systems Manager &amp; Developer at the CoL Secretariat, University of Reading, UK</p>

<p>Under coordination of Yuri Roskov at the CoL Secretariat, University of Reading, UK</p>
<br/>
<p class="field_header">Annual Checklist Software Development</p>
<p>&#8226; <b><em>Wouter Addink</em></b>, Leader of the Annual Checklist Software Development and Software Production at ETI Bioinformatics, Amsterdam, The Netherlands</p>
<p>&#8226; <b><em>Dennis Seijts</em></b>, Annual Checklist Interface Development at ETI Bioinformatics, Amsterdam, The Netherlands</p>
<p>&#8226; <b><em>Gideon Gijswijt</em></b>, Annual Checklist DVD Master and Installation Development at ETI Bioinformatics, Amsterdam, The Netherlands</p>
<p>&#8226; <b><em>Ruud Altenburg</em></b>, author of Base Schema Conversion Software at ETI BioInformatics, Amsterdam, the Netherlands</p>
<p>&#8226; <b><em>N&uacute;ria Torrescasana Aloy</em></b>, former author of the Annual Checklist Software at ETI BioInformatics, Amsterdam, the Netherlands</p>
<p>&#8226; <b><em>Richard White</em></b>, author of the Taxon Matcher Software at Cardiff University, UK</p>
<p>&#8226; <b><em>Viktoras Did&#382;iulis</em></b>, design of new data assembly workflow, author of the CoL Workbench, at University of Reading, UK.</p>
<br />
<p>&#8226; <b><em>Paul Klinkenberg</em></b>, Annual Checklist Cover Design and DVD Production at ETI Bioinformatics, Amsterdam, The Netherlands</p>

</div>
<?php
echo $this->navigator_bottom;