<?php
/**
 * Annual Checklist Interface
 *
 * cite.phtml
 * Info - How to cite this work page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Cite_work')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">

<p class="field_header">How to cite the Catalogue of Life on DVD:</p> 
<p>Bisby F., Roskov Y., Culham A., Orrell T., Nicolson D., Paglinawan L., Bailly N., Appeltans W., Kirk P., Bourgoin T., Baillargeon G., Ouvrard D., eds (2012). Species 2000 & ITIS Catalogue of Life, 2012 Annual Checklist. DVD; Species 2000: Reading, UK.</p> 

<p class="field_header">How to cite the Catalogue of Life on the Web:</p>
<p>
 Bisby F., Roskov Y., Culham A., Orrell T., Nicolson D., Paglinawan L., Bailly N., Appeltans W., Kirk P., Bourgoin T., Baillargeon G., Ouvrard D., eds (2012). Species 2000 & ITIS Catalogue of Life, 2012 Annual Checklist. Digital resource at www.catalogueoflife.org/col/. Species 2000: Reading, UK. 
</p>

<p class="field_header">How to cite the Catalogue of Life Taxonomic Classification:</p>
<p>
 Ruggiero M., Gordon D., Bailly N., Kirk P., Nicolson D. (2011). 
The Catalogue of Life Taxonomic Classification, Edition 2, Part A. In: Species 2000 & 
ITIS Catalogue of Life, 2011 Annual Checklist (Bisby F.A., Roskov Y.R., Culham A., Orrell T.M., Nicolson D., 
Paglinawan L.E., Bailly N., Appeltans W., Kirk P.M., Bourgoin T., Baillargeon G., Ouvrard D., eds). 
DVD; Species 2000: Reading, UK.
</p>



<p class="field_header">How to cite individual databases included in this work:</p>


<?php include 'citelist.html'?>
</div>
<?php
echo $this->navigator_bottom;
?>