<?php
/**
 * Annual Checklist Interface
 *
 * layout.phtml
 * Defines the global layout
 *
 * @category    ACI
 * @package     application
 * @subpackage  views
 *
 */
?>
<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php
    echo $this->headMeta();
    echo $this->headTitle();
    echo $this->headStyle();
    $this->headLink()->appendStylesheet(
        $this->baseUrl() . '/styles/style-ie6.css', 'screen', 'IE 6'
    );
    $this->headLink()->appendStylesheet(
        $this->baseUrl() . '/styles/style-ie7.css', 'screen', 'IE 7'
    );
    if ($this->dojo()->isEnabled()) {
        $this->dojo()->setLocalPath(
            $this->baseUrl() . '/scripts/library/dojo/dojo/dojo.js'
        )->addStyleSheetModule('dijit.themes.tundra');
   	    echo $this->dojo();
   	    // ComboBox (v1.3.2) custom extension
   	    $this->headScript()->appendFile(
   	        $this->baseUrl() . '/scripts/library/ComboBox.ext.js'
   	    );
    }
    echo $this->headScript()->appendFile(
        $this->baseUrl() . '/scripts/menu.js'
    );
    echo $this->headLink()->appendStylesheet(
        $this->baseUrl() . '/styles/style.css'
    );    
    ?>
</head>
<body class="tundra">
    <div id="header">
        <img src="<?php echo $this->baseUrl(); ?>/images/Annual_Checklist_Top_Banner.gif" />
    </div>
    <div id="menu" class="view">
        <span id="log"></span>
        <ul id="nav">
          <li class="<?php echo $this->controller == 'browse' ?
                'menuselected' : ''; ?>">
            <a href="<?php echo $this->baseUrl() ?>/browse/tree">
            <span class="menu_icon"><img src="<?php echo $this->baseUrl(); ?>/images/Icon_Browse.gif" /></span>
            <span><?php echo $this->translate('Browse'); ?><span></a>
            <ul>
              <li class="<?php echo $this->action == 'tree' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/browse/tree">
              <?php echo $this->translate('Taxonomic_tree'); ?></a></li>
              <li class="<?php echo $this->action == 'classification' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/browse/classification">
              <?php echo $this->translate('Taxonomic_classification'); ?></a></li>
            </ul>
          </li>
          <li class="<?php echo $this->controller == 'search' ?
                'menuselected' : ''; ?>">
            <a href="<?php echo $this->baseUrl(); ?>/search/all">
            <img src="<?php echo $this->baseUrl(); ?>/images/Icon_Search.gif" />
            <span><?php echo $this->translate('Search'); ?></span></a>
            <ul>
              <li class="<?php echo $this->action == 'all' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/search/all">
              <?php echo $this->translate('Search_all_names'); ?></a></li>
              <li class="<?php echo $this->action == 'scientific' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/search/scientific">
              <?php echo $this->translate('Search_scientific_names'); ?></a></li>
              <li class="<?php echo $this->action == 'common' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/search/common">
              <?php echo $this->translate('Search_common_names'); ?></a></li>
              <li class="<?php echo $this->action == 'distribution' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/search/distribution">
              <?php echo $this->translate('Search_distribution'); ?></a></li>
            </ul>
          </li>
          <li class="<?php echo $this->controller == 'info' ?
                'menuselected' : ''; ?>">
            <a href="<?php echo $this->baseUrl(); ?>/info/about">
            <img src="<?php echo $this->baseUrl(); ?>/images/Icon_Info.gif" />
            <span><?php echo $this->translate('Info'); ?></span></a>
            <ul>
              <li class="<?php echo $this->action == 'about' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/about">
                  <?php echo $this->translate('Info_about'); ?></a></li>
              <li class="<?php echo $this->action == 'ac' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/ac">
                  <?php printf($this->translate('Info_annual_checklist'),
                      $this->app->version); ?></a></li>
              <li class="<?php echo $this->action == 'databases' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/databases">
                  <?php echo $this->translate('Source_databases'); ?></a></li>
              <li class="<?php echo $this->action == 'hierarchy' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/hierarchy">
                  <?php echo $this->translate('Management_hierarchy'); ?></a></li>
              <li class="<?php echo $this->action == 'copyright' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/copyright">
                <?php echo $this->translate('Copyright_reproduction_sale'); ?></a></li>
              <li class="<?php echo $this->action == 'cite' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/cite">
                <?php echo $this->translate('Cite_work'); ?></a></li>
              <li class="<?php echo $this->action == 'websites' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/websites">
                <?php echo $this->translate('Web_sites'); ?></a></li>
              <li class="<?php echo $this->action == 'contact' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/contact">
                <?php echo $this->translate('Contact_us'); ?></a></li>
              <li class="<?php echo $this->action == 'acknowledgements' ?
                'menuselected' : ''; ?>"><a href="<?php echo $this->baseUrl(); ?>/info/acknowledgements">
                <?php echo $this->translate('Acknowledgements'); ?></a></li>
            </ul>
          </li>
        </ul>
    </div>
    <div id="right-col">
        <div id="content" class="view <?php echo isset($this->contentClass) ? $this->contentClass : ''; ?>">
            <?php echo $this->layout()->content; ?>
            <?php echo $this->inlineScript(); ?>
        </div>
    </div>
</body>
</html>