
<div class="page_header">
<?php echo "Literature references in BHL-Europe: {$this->bhl->numFound} found (unvetted)"; ?>
</div>


<?php
foreach($this->bhl->references as $reference) {
    $rowClass = 'odd';
/*    
	$url = sprintf($this->portalUrlPattern, $reference->pid);
	$imgUrl = null;
	$id = substr($reference->pid, (strpos($reference->pid, '-')+1));
	if($id) {
		$imgUrl = sprintf($this->imageUrlPattern, $id);
		// make sure image exists
		$h = fopen($imgUrl, 'r');
		if(!$h) {
			$imgUrl = null;
		}
		else {
			fclose($h);
		}
	}
*/		
?>

<table class="details-table">

<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical" style="width:20%;"><?php echo $this->translate('Author'); ?>:</th>
        <td><?php echo $reference->author; ?></td>
        
        <?php if($reference->imgUrl !== null) { ?>
        <td class="bhl-indent" rowspan="5">
            <a href="<?php echo $reference->url; ?>" target="_blank">
            <img src="<?php echo $reference->imgUrl; ?>" class="bhl-thumb" />
            </a>
        </td>
        <?php } ?>
    </tr>
    
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Title'); ?>:</th>
        <td><?php echo $reference->title; ?></td>
    </tr>
        
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Year'); ?>:</th>
        <td><?php echo $reference->year; ?></td>
        </tr>
    
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('Publisher'); ?>:</th>
        <td><?php echo $reference->publisher; ?></td>
        </tr>
            
<?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical"><?php echo $this->translate('URL'); ?>:</th>
        <td><a href="<?php echo $url; ?>" target="_blank"><?php echo $reference->url; ?></a></td>
        </tr>
</table>
<?php
	}
?>




<div class="page_links">
<a href="javascript:history.back()">
    <?php echo $this->translate('Back_to_last_page'); ?>
</a> |
<a href="<?php echo $this->baseUrl() . '/' . $this->latestSearch; ?>">
    <?php echo $this->translate('New_search'); ?>
</a>
</div>