<?php
echo $this->translate('Scientific_name') . $this->tab .
     $this->translate('Name_status') . $this->tab .
     $this->translate('Group') . $this->tab .
     $this->translate('Source_database') . PHP_EOL;
foreach($this->data as $k => $data) {
    echo $data['name'] . $this->tab .
         $data['status'] . $this->tab .
         $data['kingdom'] . $this->tab .
         $data['db_name'] . PHP_EOL;
         unset($this->data[$k]);
}