<!-- The <?php echo $this->app->version; ?> Annual Checklist -->

<div class="page_header">
<?php printf($this->translate('The_2009_Annual_Checklist'), '"' . $this->key . '"') ?>
</div>
<br/>

<div align=center>
    <input type='button' name='goPrev' class='formbutton' value='<< Previous' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/about'">
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <select name='select_page' onchange='document.location.href=this.options[this.selectedIndex].value'>
        <option value='<?php echo $this->baseUrl(); ?>/info/about'>About the Catalogue of Life</option>
        <option selected value='<?php echo $this->baseUrl(); ?>/info/ac'>About the 2009 Annual Checklist</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/databases'>Source databases</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/hierarchy'>Towards Management Hierarchy</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/copyright'>Copyrights, reproduction & sale</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/cite'>How to cite this work</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/websites'>Web sites</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/contact'>Contact us</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/acknowledgements'>Acknowledgements</option>
    </select>
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <input type='button' name='goNext' class='formbutton' value=' Next >> ' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/databases'">
</div>
<br />

<img src="<?php $this->baseUrl(); ?>/aci/images/2009_checklist_cd_front_cover.jpg"
    alt="<?php echo $this->placeholder($this->translate('2009_Annual_Checklist_CD-ROM_front_cover')); ?>"
    vspace="5" width="320" align="right" border="0" height="320" hspace="5"> 

<p style="margin-bottom: 20px;"><?php echo $this->placeholder($this->translate('The_2009_Annual_Checklist_contains_contributions_from_count_databases_with_information')); ?></p>

<p><b class="fieldheader"><?php echo $this->translate('Viruses'); ?></b>
 &#8226; <?php echo $this->placeholder($this->translate('Viruses_and_Subviral_agents_from_ICTV_MSL')); ?>
</p><br />

<p><?php echo $this->placeholder($this->translate('Bacteria_and_Archaea_from_BIOS')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Blue-green_algae_Cyanobacteria_from_AlgaeBase')); ?>
</p><br />

<p><b class="fieldheader"><?php echo $this->placeholder($this->translate('Chromista')); ?></b>
 &#8226; <?php echo $this->placeholder($this->translate('Chromistan_fungi_from_Species_Fungorum')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Chromistan_algae_from_AlgaeBase')); ?>
</p><br />

<p><b class="fieldheader"><?php echo $this->placeholder($this->translate('Protozoa')); ?></b>
 &#8226; <?php echo $this->placeholder($this->translate('Major_groups_from_ITIS_and_AlgaeBase')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Protozoan_fungi_from_Species_Fungorum_and_Trichomycetes_database')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Slime_moulds_from_Nomen.eumycetozoa.com')); ?>
</p><br />

<p><b class="fieldheader"><?php echo $this->placeholder($this->translate('Fungi')); ?></b>
 &#8226; <?php echo $this->placeholder($this->translate('Various_taxa_in_whole_or_in_part_from_CABI_Bioscience_databases')); ?>
</p><br />

<p><b class="fieldheader"><?php echo $this->placeholder($this->translate('Plantae_Plants')); ?></b>
 &#8226; <?php echo $this->placeholder($this->translate('Mosses_from_MOST')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Conifers_from_Conifer_Database')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Cycads_and_6_flowering_plant_families_from_IOPI-GPC_and_94_families_from_World_Checklist_of_Selected_Plant_Families')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Plus_individual_groups_Custard_Apple_family_AnnonBase_Brazil_Nut_family_LecyPages')); ?>
</p><br />

<p><b class="fieldheader"><?php echo $this->placeholder($this->translate('Animalia_Animals')); ?></b>
 &#8226; <?php echo $this->placeholder($this->translate('Sponges_from_WoRMS_Porifera')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Marine_invertebrates_12_phyla_10_classes_and_chordates_4_classes_from_URMO')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Sea_anemones_from_the_Hexacorallians_of_the_World')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Rotifers_from_Rotifera_database')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Entoprocts_cycliophorans_velvet_worms_water_bears_from_ITIS')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Shrimps_krill_cumaceans_from_ITIS_ETI_WBD_Euphausiacea_WoRMS')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Spiders_scorpions_ticks_mites_from_SpidCat_ITIS_TicksBase_Mites_GSDs')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Diplopods_centipedes_pauropods_and_symphylans_from_SysMyr_and_ChiloBase')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Dragonflies_and_damselflies_from_the_Odonata_database')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Stoneflies_from_PlecopteraSF')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Cockroaches_from_BSF')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Praying_mantids_from_MSF')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Stick_and_leaf_insects_from_PSF')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Grasshoppers_locusts_katydids_and_crickets_from_OSF')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Some_groups_of_true_bugs_from_ScaleNet_FLOW_COOL_Psyllist_ASF')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Lacewings_antlions_owlflies_fishflies_dobsonflies_snakeflies_from_LDL_Neuropterida')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Some_beetle_groups_from_the_Scarabs_Database_TITAN_WTaxa_ITIS')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Fleas_from_Parhost')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Flies_mosquitoes_bots_midges_and_gnats_from_BDWD_CCW_CIPA')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Butterflies_and_moths_from_LepIndex_GloBIS_GART_Tineidae_NHM_World_Gracillariidae')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Bees_and_wasps_from_ITIS_UCD_and_ZOBODAT')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Snails_and_slugs_from_AFD')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Horseshoe_worms_lamp-shells_brittle_and_basket_stars_from_WoRMS')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Fishes_from_FishBase')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Reptiles_from_TIGR_Reptiles')); ?>
 &#8226; <?php echo $this->placeholder($this->translate('Amphibians_birds_and_mammals_from_ITIS')); ?>
</p><br />

<p><?php echo $this->placeholder($this->translate('PLUS_additional_species_of_many_groups_from_ITIS')); ?>
</p><br />

<p><b><?php echo $this->placeholder($this->translate('Structure_of_the_Annual_Checklist')); ?></b>
</p><br />

<p><?php echo $this->placeholder($this->translate('The_goal_is_to_list_every_distinct_species_in_each_group_of_organisms')); ?>
</p><br />

<div class="copyright_notice">
<p><?php echo $this->placeholder($this->translate('Definition_of_a_Global_Species_Database_GSD')); ?>
</p><br />

<p><?php echo $this->placeholder($this->translate('GSDs_aspire_to_the_following_properties')); ?></p>
<p>&#8226; <?php echo $this->placeholder($this->translate('Cover_one_taxon_worldwide')); ?><br />
&#8226; <?php echo $this->placeholder($this->translate('Contain_a_taxonomic_checklist_of_all_species_within_that_taxon')); ?><br />
&#8226; <?php echo $this->placeholder($this->translate('Deal_with_species_as_taxa_and_contain_synonymy_and_taxonomic_opinion')); ?><br />
&#8226; <?php echo $this->placeholder($this->translate('Have_an_explicit_mechanism_for_seeking_at_least_one_responsible_consensus_taxonomy_and_for_applying_it_consistently')); ?><br />
&#8226; <?php echo $this->placeholder($this->translate('Cross-index_significant_alternative_taxonomies_in_their_synonymy')); ?>
</p>
</div><br />

<p><?php echo $this->placeholder($this->translate('Each_species_is_linked_via_the_genus_and_family_to_the_taxonomic_classification')); ?><br />
<?php echo $this->placeholder($this->translate('Please_also_read_the_draft_discussion_document')); ?>
</p><br />

<div class="copyright_notice">
<p><?php echo $this->placeholder($this->translate('The_Catalogue_of_Life_Standard_Dataset')); ?>
</p><br />

<p><?php echo $this->placeholder($this->translate('Accepted_scientific_name_and_reference')); ?><br />
<?php echo $this->placeholder($this->translate('Synonyms_and_references')); ?><br />
<?php echo $this->placeholder($this->translate('Common_names_and_references')); ?><br />
<?php echo $this->placeholder($this->translate('Latest_taxonomic_scrutiny_name_of_person_and_date')); ?><br />
<?php echo $this->placeholder($this->translate('Source_database')); ?><br />
<?php echo $this->placeholder($this->translate('Additional_data_optional')); ?><br />
<?php echo $this->placeholder($this->translate('Family_to_which_species_belongs')); ?><br />
<?php echo $this->placeholder($this->translate('Classification_above_family_and_highest_taxon_in_database')); ?><br />
<?php echo $this->placeholder($this->translate('Distribution')); ?><br />
<?php echo $this->placeholder($this->translate('References_optional')); ?><br />
<?php echo $this->placeholder($this->translate('LSID')); ?>
</p>
</div><br />

<p><?php echo $this->placeholder($this->translate('More_detailed_information_about_the_Standard_Dataset_is_available')); ?>.
</p><br />

<p><?php echo $this->placeholder($this->translate('Each_species_is_linked_via_the_genus_and_family_to_the_taxonomic_classification')); ?>.
</p><br />

<p><?php echo $this->placeholder($this->translate('Where_available_from_the_suppliers_infraspecific_taxa_such_as_subspecies')); ?>.
</p><br />

<p><?php echo $this->placeholder($this->translate('Where_possible_a_web_link_back_to_the_suppliers_own_database')); ?>.
</p><br />

<p><strong><?php echo $this->placeholder($this->translate('CoL_Taxon_Identifiers_Taxon_LSIDs')); ?>.</strong>
</p><br />

<p><?php echo $this->placeholder($this->translate('The_Catalogue_of_Life_programme_started_to_issue_permanent')); ?>.
</p><br />

<p><?php echo $this->placeholder($this->translate('Where_a_taxon_record_remains_unchanged_in_this_2009_edition')); ?>.
</p><br />

<p><?php echo $this->placeholder($this->translate('Our_LSIDs_are_long_strings_of_symbols_intended_only_for_computer_usage')); ?>.
</p><br />



<p><b><?php echo $this->placeholder($this->translate('Functionality_of_the_Annual_Checklist')); ?>.</b>
</p><br />

<p>&#8226; <?php echo $this->placeholder($this->translate('Species_and_infraspecific_taxa_can_be_located_either')); ?>.<br />
&#8226; <?php echo $this->placeholder($this->translate('Searching_by_name_can_be_done_using_accepted_scientific')); ?>.<br />
&#8226; <?php echo $this->placeholder($this->translate('Tracking_down_the_tree_or_classification_uses_accepted_names_for_taxa')); ?>.<br />
&#8226;  <?php echo $this->placeholder($this->translate('On_each_species_details_page_the_relevant_higher_taxa_are_listed')); ?>.<br />
&#8226;  <?php echo $this->placeholder($this->translate('The_species_details_pages_link_to_the_source_database')); ?>.
</p><br />

<p><?php echo $this->placeholder($this->translate('This_CD_contains_the_Annual_Checklist_dataset_and_the_software')); ?>.
</p><br />

<p><b><?php echo $this->placeholder($this->translate('The_2009_Annual_Checklist_Editors')); ?>.</b>
</p><br />

<p><?php echo $this->placeholder($this->translate('The_Catalogue_of_Life_programme_combines_the_outputs')); ?>.
</p><br />

<p>&#8226; <?php echo $this->placeholder($this->translate('Frank_Bisby_Species_2000_Executive_Director')); ?>
</p><br />

<p>&#8226; <?php echo $this->placeholder($this->translate('Yuri_Roskov_Executive_Editor_at_the_Species_2000')); ?>
</p><br />

<p>&#8226;  <?php echo $this->placeholder($this->translate('Thomas_Orrell_Acting_Director_ITIS_at_the_ITIS_Secretariat')); ?>
</p><br />

<p>&#8226;  <?php echo $this->placeholder($this->translate('David_Nicolson_ITIS_Data_Development_Leader')); ?>
</p><br />

<p>&#8226;  <?php echo $this->placeholder($this->translate('Luvie_Paglinawan_Annual_Checklist_Dataset_Compiler')); ?>
</p><br />

<p>&#8226;  <?php echo $this->placeholder($this->translate('Nicolas_Bailly_Taxonomic_Editorial_Advisor_for_Marine_sectors')); ?>
</p><br />

<p>&#8226;  <?php echo $this->placeholder($this->translate('Paul_Kirk_Taxonomic_Editorial_Advisor_for_Fungi')); ?>
</p><br />

<p>&#8226;  <?php echo $this->placeholder($this->translate('Thierry_Bourgoin_Taxonomic_Editorial_Advisor_for_Insects')); ?>
</p><br />

<p>&#8226;  <?php echo $this->placeholder($this->translate('Guy_Baillargeon_Taxonomic_Editorial_Advisor_for_Plants')); ?>
</p>

<div class="horizontal_line"><br /></div><br />
<div align=center>
    <input type='button' name='goPrev' class='formbutton' value='<< Previous' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/about'">
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <select name='select_page' onchange='document.location.href=this.options[this.selectedIndex].value'>
        <option value='<?php echo $this->baseUrl(); ?>/info/about'>About the Catalogue of Life</option>
        <option selected value='<?php echo $this->baseUrl(); ?>/info/ac'>About the 2009 Annual Checklist</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/databases'>Source databases</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/hierarchy'>Towards Management Hierarchy</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/copyright'>Copyrights, reproduction & sale</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/cite'>How to cite this work</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/websites'>Web sites</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/contact'>Contact us</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/acknowledgements'>Acknowledgements</option>
    </select>
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <input type='button' name='goNext' class='formbutton' value=' Next >> ' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/databases'">
</div>