<div class="page_header">
<?php
printf($this->translate('Info_annual_checklist'), $this->app->version);
?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content"><img
    src="<?php
    echo $this->baseUrl();
    ?>/images/2009_checklist_cd_front_cover.jpg"
    title="2009 Annual Checklist CD-ROM front cover"
    alt="2009 Annual Checklist CD-ROM front cover" width="320"
    height="320" class="right-align" />
<p style="margin-bottom: 20px;">The 2009 Annual Checklist contains
contributions from 66 databases with information on [b]1,160,711</b>
species and <b>75,772</b> infraspecific taxa, and also includes <b>763,776</b>
synonyms and <b>469,891</b> common names covering the following groups:</p>
<p><b class="field_header">Viruses</b>
 &#8226; <?php
echo $this->placeholder('Viruses and Subviral agents from [link:db:14]');
?>
</p>
<p><b class="field_header">Bacteria</b> and <b class="field_header">Archaea</b> from
<?php
echo $this->placeholder('[link:db:4]');
?>
 &#8226; <?php
echo $this->placeholder('Blue-green algae (Cyanobacteria) from [link:db:2]');
?>
</p>
<p><b class="field_header">Chromista</b>
 &#8226; <?php
echo $this->placeholder('Chromistan fungi from [link:db:28]');
?>
 &#8226; <?php
echo $this->placeholder('Chromistan algae from [link:db:2]');
?>
</p>
<p><b class="field_header">Protozoa</b>
 &#8226; <?php
echo $this->placeholder('Major groups from [link:db:17] and [link:db:2]');
?>
 &#8226; <?php
echo $this->placeholder('Protozoan fungi from [link:db:28] and [link:db:33] database');
?>
 &#8226; <?php
echo $this->placeholder('Slime moulds from [link:db:53]');
?>
</p>
<p><b class="field_header">Fungi</b>
 &#8226; <?php
echo $this->placeholder('Various taxa in whole or in part from CABI Bioscience databases ([link:db:28], [link:db:23], [link:db:25] and [link:db:38] databases) and from three other databases covering [link:db:36], [link:db:12] and [link:db:33]');
?>
</p>
<p><b class="field_header">Plantae (Plants)</b>
 &#8226; <?php
echo $this->placeholder('Mosses from [link:db:19]');
?>
 &#8226; <?php
echo $this->placeholder('Conifers from [link:db:45]');
?>
 &#8226; <?php
echo $this->placeholder('Cycads and 6 flowering plant families from [link:db:16] and 94 families from [link:db:24]');
?>
 &#8226; <?php
echo $this->placeholder('Plus individual groups: Custard Apple family ([link:db:40]) , Brazil Nut family ([link:db:43]), Sundew family ([link:db:66] [new]), Waits Numi family ([link:db:56] [new]), Legumes ([link:db:15]), Cranesbills ([link:db:48]) and Nightshade genus ([link:db:64] [new])');
?>
</p>
<p><b class="field_header">Animalia (Animals)</b>
 &#8226; <?php
echo $this->placeholder('Sponges from [link:db:44]');
?>
 &#8226; <?php
echo $this->placeholder('Marine invertebrates (12 phyla & 10 classes ) and chordates (4 classes) from [link:db:35]');
?>
 &#8226; <?php
echo $this->placeholder('Sea anemones from the [link:db:13]');
?>
 &#8226; <?php
echo $this->placeholder('Rotifers from [link:db:47]');
?>
 &#8226; <?php
echo $this->placeholder('Entoprocts, cycliophorans, velvet worms, water bears from [link:db:17]');
?>
 &#8226; <?php
echo $this->placeholder('Shrimps, krill, cumaceans [new] from [link:db:17], [link:db:9] (Euphausiacea), [link:db:58]');
?>
 &#8226; <?php
echo $this->placeholder('Spiders, scorpions, ticks & mites from [link:db:29], [link:db:17], [link:db:30], & [link:db:63]');
?>
 &#8226; <?php
echo $this->placeholder('Diplopods, centipedes, pauropods and symphylans from [link:db:41] and [link:db:42]');
?>
 &#8226; <?php
echo $this->placeholder('Dragonflies and damselflies from the [link:db:20] database');
?>
 &#8226; <?php
echo $this->placeholder('Stoneflies from [link:db:65] [new]');
?>
 &#8226; <?php
echo $this->placeholder('Cockroaches from [link:db:51]');
?>
 &#8226; <?php
echo $this->placeholder('Praying mantids from [link:db:62] [new]');
?>
 &#8226; <?php
echo $this->placeholder('Stick and leaf insects from [link:db:50]');
?>
 &#8226; <?php
echo $this->placeholder('Grasshoppers, locusts, katydids and crickets from [link:db:21]');
?>
 &#8226; <?php
echo $this->placeholder('Some groups of true bugs from [link:db:26], [link:db:11], [link:db:52], [link:db:54] [new] & ASF [new]');
?>
 &#8226; <?php
echo $this->placeholder('Lacewings, antlions, owlflies, fishflies, dobsonflies & snakeflies from [link:db:55] [new]');
?>
 &#8226; <?php
echo $this->placeholder('Some beetle groups from the [link:db:27], [link:db:40], [link:db:39] & [link:db:17]');
?>
 &#8226; <?php
echo $this->placeholder('Fleas from [link:db:22]');
?>
 &#8226; <?php
echo $this->placeholder('Flies, mosquitoes, bots, midges and gnats from [link:db:3], [link:db:5] & [link:db:6]');
?>
 &#8226; <?php
echo $this->placeholder('Butterflies and moths from [link:db:18], [link:db:46], [link:db:31], [link:db:49]');
?>
 &#8226; <?php
echo $this->placeholder('Bees [new] and wasps from [link:db:67], [link:db:34] and [link:db:37]');
?>
 &#8226; <?php
echo $this->placeholder('Snails and slugs from [link:db:1]');
?>
 &#8226; <?php
echo $this->placeholder('Horseshoe worms, lamp-shells, brittle and basket stars from [link:db:57] [new]');
?>
 &#8226; <?php
echo $this->placeholder('Fishes from [link:db:10]');
?>
 &#8226; <?php
echo $this->placeholder('Reptiles from [link:db:8]');
?>
 &#8226; <?php
echo $this->placeholder('Amphibians, birds and mammals from [link:db:17]');
?>
</p>
<p><span class="field_header">PLUS</span> additional species of many groups from <?php
echo $this->placeholder('[link:db:17]');
?>
</p>
<p><b>Structure of the Annual Checklist</b></p>
<p>The goal is to list every distinct species in each group of
organisms. At present, some groups are globally complete, some are
represented by global sectors that are nearing completion, and others
are represented by partial sectors. The global sectors, whether complete
or not, are provided by selected, peer reviewed global species databases
(GSDs - see definition below) in the Species 2000 federation or by
equivalent global sectors of ITIS. The partial sectors are supplied
principally by ITIS (N America), but also Species Fungorum and the
Australian Faunal Directory, with the result that N American species are
sometimes the only species represented for these incomplete groups.</p>
<div class="copyright_notice">Definition of a Global Species Database
(GSD)
<p>GSDs aspire to the following properties</p>
<p>&#8226; Cover one taxon worldwide<br />
&#8226; Contain a taxonomic checklist of all species within that taxon<br />
&#8226; Deal with species as taxa, and contain synonymy and taxonomic
opinion<br />
&#8226; Have an explicit mechanism for seeking at least one
responsible/consensus taxonomy, and for applying it consistently<br />
&#8226; Cross-index significant alternative taxonomies in their synonymy</p>
</div>
<p>Each species is linked via the genus and family to the taxonomic
classification. Above the node of attachment of each data sector this
classification has been agreed by Species 2000 and ITIS as a practical
management tool to provide access to the Catalogue, the Catalogue of
Life Taxonomic Classification Edition 1. This top level classification
has remained unchanged in 2005-2009. However, below the nodes of
attachment for each taxonomic sector, the classification originates from
the supplier databases and so may change from year to year. Because of
these lower level changes there are therefore annual versions of Edition
1 for 2005, 2006, 2007, 2008 and 2009. Please also read the draft
discussion document <a
    href="<?php
    echo $this->baseUrl();
    ?>/info/hierarchy">Towards a management hierarchy (classification)
for the Catalogue of Life</a> by Dennis Gordon appended to this edition
of the Annual Checklist.</p>
<div class="copyright_notice">The Catalogue of Life Standard Dataset
<p>(1) &nbsp;&nbsp;Accepted scientific name (and reference)<br />
(2) &nbsp;&nbsp;Synonyms (and references)<br />
(3) &nbsp;&nbsp;Common names (and references)<br />
(4) &nbsp;&nbsp;Latest taxonomic scrutiny (name of person and date)<br />
(5) &nbsp;&nbsp;Source database<br />
(6) &nbsp;&nbsp;Additional data (optional)<br />
(7) &nbsp;&nbsp;Family to which species belongs<br />
(8) &nbsp;&nbsp;Classification above family, and highest taxon in
database<br />
(9) &nbsp;&nbsp;Distribution<br />
(10) Reference(s) (optional)<br />
(11) LSID</p>
</div>
<p>More detailed information about the Standard Dataset is available on
the Species 2000 website (<a href="http://www.sp2000.org">www.sp2000.org</a>)</p>
<p>Each species is linked via the genus and family to the taxonomic
classification. Above the node of attachment of each data sector this
classification has been agreed by Species 2000 and ITIS as a practical
management tool to provide access to the Catalogue, the Catalogue of
Life Taxonomic Classification Edition 1. This top level classification
has remained unchanged in 2005-2009. However, below the node of
attachment the classification originates from the supplier databases and
so may change from year to year. Because of this lower level changes
there are therefore annual versions of Edition 1 for 2005, 2006, 2007,
2008 and 2009.</p>
<p>Where available from the suppliers, infraspecific taxa such as
subspecies and varieties have also been included but this coverage is
variable between taxonomic sectors.</p>
<p>Where possible, a web link back to the supplier's own database is
provided at the bottom of each species detail page.</p>
<p><b>CoL Taxon Identifiers (Taxon LSIDs)</b></p>
<p>he Catalogue of Life programme started to issue permanent CoL Taxon
Identifiers in the 2008 Annual Checklist. Every taxon recognised in the
Catalogue, including species and higher taxa, is given a globally unique
identifier (GUID) using the Life Science Identifier (LSID) system (<a
    href="http://sourceforge.net/projects/lsids">sourceforge.net/projects/lsids</a>).
</p>
<p>Where a taxon record remains unchanged in this 2009 edition, it
carries the same LSID as in 2008, except that the revision part changes
from ac2008 to ac2009. New or changed taxa in the 2009 edition receive
completely new LSIDs. This will enable the introduction in the next few
years of change tracking between editions, so that relationships to taxa
in previous editions are recorded, and web-services to alert users to
changes in name, classification, circumscription or data. Technical
users are already able to inspect changes in the metadata provided by
the CoL LSID Resolution Service, and to build their own services using
them. For more information, see www.catalogueoflife.org/lsid/. LSIDs in
the 2009 Annual Checklist have been generated by Richard White, Cardiff
University, UK.</p>
<p>Our LSIDs are long strings of symbols intended only for computer
usage. However, the user interface does show LSID buttons (click, and
the LSID is displayed in full), and the LSID is shown at the base of
each Species Details screen. This is done so that a user can copy and
paste the LSIDs into other software or services: it is NOT intended for
them to be read or typed.</p>
<p><b>Functionality of the Annual Checklist</b></p>
<p>&#8226; Species (and infraspecific taxa) can be located either by
searching by name or by tracking down through the hierarchical
classification.<br />
&#8226; Searching by name can be done using accepted scientific name,
synonym or common name. Automatic synonymic and common name indexing
takes the user directly to the species under its accepted name. The
search can use part names, or be restricted to complete words.<br />
&#8226; Tracking down the tree or classification uses accepted names for
taxa.<br />
&#8226; On each species details page the relevant higher taxa are
listed, and provide a link to the relevant node of the hierarchical
classification.<br />
&#8226; The species details pages link to the source database, usually
showing further information.</p>
<p>This CD contains the Annual Checklist dataset and the software
identical to that used on the Web. The structure of the Annual Checklist
database has been optimised for performance with the user interface but
is not ideal for importing to other systems. The content may be copied
subject to the copyright conditions given on the inside cover of this
booklet.</p>
<p><b>The 2009 Annual Checklist Editors</b></p>
<p>The Catalogue of Life programme combines the outputs of the Species
2000 programme (led by Frank Bisby from Reading, UK) and the ITIS
programme (led by Thomas Orrell from Washington, USA). Assembly and
publication of the Annual Checklist is managed by Yuri Roskov in Reading
working with colleagues around the world.</p>
<p>&#8226; <b>Frank Bisby</b>, Species 2000 Executive Director and Team member, at the Species 2000 Secretariat, Reading, UK</p>
<p>&#8226; <b>Yuri Roskov</b>, Executive Editor at the Species 2000 Secretariat, Reading, UK</p>
<p>&#8226; <b>Thomas Orrell</b>, Acting Director, ITIS at the ITIS Secretariat, Smithsonian Institution, Washington DC, USA</p>
<p>&#8226; <b>David Nicolson</b>, ITIS Data Development Leader, USGS/Smithsonian Institution, Washington DC, USA</p>
<p>&#8226; <b>Luvie Paglinawan</b>, Annual Checklist Dataset Compiler, at the Species 2000 Philippines Office, WorldFish Center, Los-Baños, Philippines</p>
<p>&#8226; <b>Nicolas Bailly</b>, Taxonomic Editorial Advisor for Marine sectors and Species 2000 Philippines Office Manager at the WorldFish Center, Los-Baños, Philippines</p>
<p>&#8226; <b>Paul Kirk</b>, Taxonomic Editorial Advisor for Fungi and Chromista sectors at CABI, Egham, UK</p>
<p>&#8226; <b>Thierry Bourgoin</b>, Taxonomic Editorial Advisor for Insects at the Museum National d'Histoire Naturelle, Paris, France</p>
<p>&#8226; <b>Guy Baillargeon</b>, Taxonomic Editorial Advisor for Plants at Agriculture and Agri-Food Canada</p>
</div>
<div class="horizontal_line"><br />
</div>
<?php
echo $this->navigator_bottom;
?>