<div class="page_header">
<?php echo $this->translate('Acknowledgements') ?>
</div>
<br/>

<div align=center>
    <input type='button' name='goPrev' class='formbutton' value='<< Previous' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/contact'">
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <select name='select_page' onchange='document.location.href=this.options[this.selectedIndex].value'>
        <option value='<?php echo $this->baseUrl(); ?>/info/about'>About the Catalogue of Life</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/ac'>About the 2009 Annual Checklist</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/databases'>Source databases</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/hierarchy'>Towards Management Hierarchy</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/copyright'>Copyrights, reproduction & sale</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/cite'>How to cite this work</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/websites'>Web sites</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/contact'>Contact us</option>
        <option selected value='<?php echo $this->baseUrl(); ?>/info/acknowledgements'>Acknowledgements</option>
    </select>
</div>
<br />

<p>The Catalogue of Life partnership  thanks all who contributed to the content and production of this Annual Checklist. In particular, thanks this year to Encyclopedia of Life and SBNO for their contributions to the preparation, in addition to NBII, University of Reading (Centre for Plant Diversity and Systematics), European Commission (EC EDIT NoE and Key2Nature), WorldFish Center (SeaLifeBase project), NIES and ETI BioInformatics.
</p>

<p> Publication of the CD coincides with the start of our next major European Commission project. The 4D4Life Project (Distributed Dynamic Diversity Databases for Life) runs from 2009 to 2012.
</p>

<p>Thanks also go to <strong>Jorrit van Hertum</strong>, author of the Annual Checklist software, <strong>Gideon Gijswijt</strong>, <strong>Wouter Addink</strong> (ETI BioInformatics) and <strong>Peter Brewer</strong> (Cornell University) for technical assistance, and to <strong>Paul Klinkenberg </strong>(ETI BioInformatics) for the cover design.
</p>

<p>Very special thanks are addressed to <strong>David Eades</strong> (principal database developer of Species Files), <strong>Ward Appeltans</strong> (data manager of WoRMS) and <strong>Paul Kirk</strong> (coordinator of fungal databases).
</p>

<p>We would like to acknowledge all the people from the GSD community who provide us valuable support in data export and transformation this year: <strong>Angel Anta</strong>, <strong>Richard Flood</strong>, <strong>Johannes Goll</strong>, <strong>Alexander Kroupa</strong>, <strong>Bart Vanhoorne</strong> and<strong> Lisa Walley</strong>, as well as those acknowledged in the two preceding years: <strong>Rosario Dioguardi</strong>, <strong>Anton Güntsch,</strong> <strong>Sergey Jezniakowsky</strong>, <strong>Antonella Linguanti</strong> and <strong>Silvia Lusa</strong>. We also thank <strong>Richard White</strong> for implementation of LSIDs in the 2008 and 2009 editions.
</p>

<p>
</p>

<div style="padding-top: 25px; padding-bottom: 25px;" align="center"><img src="<?php echo $this->baseUrl(); ?>/images/2009_checklist_logos.jpg" alt="logos" usemap="#Map" width="587" border="0" height="116"></div>

<p><img src="<?php echo $this->baseUrl(); ?>/images/blank.gif" alt="" width="505" border="0" height="1">
</p>

<map name="Map">
    <area shape="rect" alt="e-infrastructure" href="http://cordis.europa.eu/fp7/ict/e-infrastructure/"coords="196,62,315,110" />
    <area shape="rect" alt="University of Reading" href="http://www.rdg.ac.uk" coords="317,59,455,113" />
    <area shape="rect" alt="FP7" href="http://ec.europa.eu/research/fp7/" coords="135,58,190,108" />
    <area shape="rect" alt="NIES" href="http://www.nies.go.jp/" coords="518,10,587,52" />
    <area shape="rect" alt="ETI" href="http://www.eti.uva.nl" coords="434,6,517,53" />
    <area shape="rect" alt="CODATA" href="http://www.codata.org" coords="313,6,363,49" />

    <area shape="rect" alt="WorldFish Center" href="http://www.worldfishcenter.org" coords="245,5,310,50" />
    <area shape="rect" alt="EDIT" href="http://www.e-taxonomy.eu/" coords="198,7,241,52" />
    <area shape="rect" alt="NBII" href="http://www.nbii.gov/" coords="127,7,196,49" />
    <area shape="rect" alt="Smithsonian Institution" href="http://www.si.edu/" coords="77,3,124,51" />
    <area shape="rect" alt="Encyclopedia of Life" href="http://www.eol.org/" coords="5,4,74,51" />
</map>

<div class="horizontal_line"><br /></div><br />
<div align=center>
    <input type='button' name='goPrev' class='formbutton' value='<< Previous' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/contact'">
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <select name='select_page' onchange='document.location.href=this.options[this.selectedIndex].value'>
        <option value='<?php echo $this->baseUrl(); ?>/info/about'>About the Catalogue of Life</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/ac'>About the 2009 Annual Checklist</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/databases'>Source databases</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/hierarchy'>Towards Management Hierarchy</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/copyright'>Copyrights, reproduction & sale</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/cite'>How to cite this work</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/websites'>Web sites</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/contact'>Contact us</option>
        <option selected value='<?php echo $this->baseUrl(); ?>/info/acknowledgements'>Acknowledgements</option>
    </select>
</div>