<?php
/**
 * Annual Checklist Interface
 *
 * acknowledgements.phtml
 * Info - Acknowledgements page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Acknowledgements')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>The Catalogue of Life partnership thanks all who contributed to the
content and production of this Annual Checklist. In particular, thanks
this year to Encyclopedia of Life and SBNO for their contributions to
the preparation, in addition to NBII, University of Reading (Centre for
Plant Diversity and Systematics), European Commission (EC EDIT NoE and
Key2Nature), WorldFish Center (SeaLifeBase project), NIES and ETI
BioInformatics.</p>

<p>Publication of the CD coincides with the start of our next major
European Commission project. The 4D4Life Project (Distributed Dynamic
Diversity Databases for Life) runs from 2009 to 2012.</p>

<p>Thanks also go to <strong>Jorrit van Hertum</strong>, author of the
Annual Checklist software, <strong>Gideon Gijswijt</strong>, <strong>Wouter
Addink</strong> (ETI BioInformatics) and <strong>Peter Brewer</strong>
(Cornell University) for technical assistance, and to <strong>Paul
Klinkenberg </strong>(ETI BioInformatics) for the cover design.</p>

<p>Very special thanks are addressed to <strong>David Eades</strong>
(principal database developer of Species Files), <strong>Ward Appeltans</strong>
(data manager of WoRMS) and <strong>Paul Kirk</strong> (coordinator of
fungal databases).</p>

<p>We would like to acknowledge all the people from the GSD community
who provide us valuable support in data export and transformation this
year: <strong>Angel Anta</strong>, <strong>Richard Flood</strong>, <strong>Johannes
Goll</strong>, <strong>Alexander Kroupa</strong>, <strong>Bart Vanhoorne</strong>
and<strong> Lisa Walley</strong>, as well as those acknowledged in the
two preceding years: <strong>Rosario Dioguardi</strong>, <strong>Anton
Güntsch,</strong> <strong>Sergey Jezniakowsky</strong>, <strong>Antonella
Linguanti</strong> and <strong>Silvia Lusa</strong>. We also thank <strong>Richard
White</strong> for implementation of LSIDs in the 2008 and 2009
editions.</p>

<div class="logobar">
    <img src="<?php echo $this->baseUrl();?>/images/ac-logobar.png" alt="logos" usemap="#Map" />
</div>
<map name="Map">
    <area shape="rect" alt="Encyclopedia of Life"
        href="http://www.eol.org/" coords="4,4,72,51" />
    <area shape="rect" alt="Smithsonian Institution"
        href="http://www.si.edu/" coords="78,4,122,53" />
    <area shape="rect" alt="NBII"
        href="http://www.nbii.gov/" coords="123,9,182,45" />
    <area shape="rect" alt="EDIT"
        href="http://www.e-taxonomy.eu/" coords="185,4,230,50" />
    <area shape="rect" alt="WorldFish Center"
        href="http://www.worldfishcenter.org" coords="232,5,294,50" />
    <area shape="rect" alt="CODATA"
        href="http://www.codata.org" coords="296,8,340,46" />
    <area shape="rect" alt="KeyToNature"
        href="http://keytonature.eu" coords="345,5,416,50" />
    <area shape="rect" alt="ETI Bioinformatics"
        href="http://www.eti.uva.nl" coords="420,8,500,50" />
    <area shape="rect" alt="NIES" href="http://www.nies.go.jp/"
        coords="504,10,568,50" />
    
    <area shape="rect" alt="FP7"
        href="http://ec.europa.eu/research/fp7/" coords="10,58,60,102" />
    <area shape="rect" alt="e-infrastructure"
        href="http://cordis.europa.eu/fp7/ict/e-infrastructure/"
        coords="64,58,178,102" />
    <area shape="rect" alt="4D4Life"
        href="http://4d4life.eu" coords="184,62,306,102" />
    <area shape="rect" alt="CDB"
        href="http://www.cbd.int" coords="308,60,430,100" />
    <area shape="rect" alt="University of Reading"
        href="http://www.rdg.ac.uk" coords="430,60,558,100" />
</map>
</div>
<?php echo $this->navigator_bottom; ?>