<?php
/**
 * Annual Checklist Interface
 *
 * cite.phtml
 * Info - How to cite this work page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<h1 class="page_header">
<?php
echo $this->translate('Cite_work')?>
</h1>
<?php
echo $this->navigator_top;
?>
<div class="info_content">

<p class="field_header">How to cite the Annual Checklist on DVD:</p>
<p>
Roskov Y., Kunze T., Orrell T., Abucay L., Paglinawan L., Culham A., Bailly N., Kirk P., Bourgoin T., Baillargeon G., Decock W., De Wever A., Did&#382;iulis V., eds. (2014). Species 2000 & ITIS Catalogue of Life, 2014 Annual Checklist. DVD. Species 2000: Naturalis, Leiden, the Netherlands.</p>

<p class="field_header">How to cite the Annual Checklist on the web:</p>
<p>
Roskov Y., Kunze T., Orrell T., Abucay L., Paglinawan L., Culham A., Bailly N., Kirk P., Bourgoin T., Baillargeon G., Decock W., De Wever A., Did&#382;iulis V., eds. (2014). Species 2000 & ITIS Catalogue of Life, 2014 Annual Checklist. Digital resource at www.catalogueoflife.org/annual-checklist/2014. Species 2000: Naturalis, Leiden, the Netherlands.</p>

<p class="field_header">How to cite the Catalogue of Life monthly edition on the Web:</p>
<p>
Roskov Y., Kunze T., Orrell T., Abucay L., Paglinawan L., Culham A., Bailly N., Kirk P., Bourgoin T., Baillargeon G., Decock W., De Wever A., Did&#382;iulis V., eds. (2014). Species 2000 & ITIS Catalogue of Life, 17th March 2014. Digital resource at www.catalogueoflife.org/col. Species 2000: Naturalis, Leiden, the Netherlands.
</p>

<p class="field_header">How to cite individual databases included in this work:</p>

<?php include 'citelist.html'?>
</div>
<?php
echo $this->navigator_bottom;
?>