<?php
/**
 * Annual Checklist Interface
 *
 * cite.phtml
 * Info - How to cite this work page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Cite_work')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>
    <span class="field_header">How to cite the Catalogue of Life on the Web: </span>
    <br />
    Bisby F.A., Roskov Y.R., Orrell T.M., Nicolson D., Paglinawan L.E., Bailly N.,
    Kirk P.M., Bourgoin T., Baillargeon G., Ouvrard D., eds (2010). Species 2000 &amp; ITIS
    Catalogue of Life, 2nd October 2010. Digital resource at
    <a href="http://www.catalogueoflife.org/col" target="_blank">http://www.catalogueoflife.org/col</a>.
    Species 2000: Reading, UK.
</p>

<p>
    <span class="field_header">How to cite the Catalogue of Life
    Taxonomic Classification: </span>
    <br />
    Bisby F.A., Roskov Y.R., Orrell T.M., Nicolson D., Paglinawan L.E., Bailly N.,
    Kirk P.M., Bourgoin T., Baillargeon G., Ouvrard D., eds (2010). Species 2000 &amp; ITIS
    Catalogue of Life: Taxonomic Classification. Digital resource at
    <a href="http://www.catalogueoflife.org/col" target="_blank">http://www.catalogueoflife.org/col</a>. Species 2000: Reading, UK.
</p>
<p>
    <span class="field_header">How to cite individual databases included
    in this work:</span>
    <br />
<p><b>AFD (Pulmonata)</b><br/>B.J. Smith, S. Reid &amp; W.F. Ponder (Pulmonata); A. Wells (ed) (2010). AFD: Australian Faunal Directory (Pulmonata) (version May 2002). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>AlgaeBase</b><br/>M. Guiry (2010). AlgaeBase (version 3.0, Dec 2004). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>AnnonBase</b><br/>H. Rainer &amp; L.W. Chatrou (eds) (2010). AnnonBase: World Species List of Annonaceae (version 1.1, Oct 2006). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ASF</b><br/>C. Favret (2010). ASF: Aphid Species File (version 1.0/3.4, Apr 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>BDWD</b><br/>N.L. Evenhuis, T. Pape, A.C. Pont &amp; F.C. Thompson (eds); T. Pape (custodian) (2010). BDWD: BioSystematic Database of World Diptera (version 11, Dec 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>BIOS</b><br/>J. Shimura, K. Hiraki &amp; G.M. Garrity (eds) (2010). BIOS: Bacteriology Insight Orienting System (version Dec 2006). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Brassicaceae</b><br/>S.I. Warwick, A. Francis &amp; I.A. Al-Shehbaz (2010). Brassicaceae species checklist and database (version 2, Oct 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>BSF</b><br/>G.W. Beccaloni (2010). BSF: Blattodea Species File Online (version 1.2/4.0, Apr 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>CCW</b><br/>P. Oosterbroek (2010). CCW: Catalogue of Craneflies of the World (version Mar 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ChiloBase</b><br/>A. Minelli (ed) (2010). ChiloBase: A World Catalogue of Centipedes (Chilopoda) for the web (version 1.01, May 2006). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>CIPA</b><br/>R. Vignes-Lebbe &amp; C. Gallut (2010). CIPA: Computer Aided Identification of Phlebotomine sandflies of Americas (version 2, Jan 1997). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Conifer Database</b><br/>A. Farjon (2010). Conifer Database (version Jul 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>COOL</b><br/>A. Soulier-Perkins (2010). COOL: Cercopoidea Organised On Line (version 4, Sep-2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>CunaxidBase</b><br/>J. den Heyer (2010). CunaxidBase: Family Cunaxidae Database (version Jan 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Droseraceae Database</b><br/>A. Culham &amp; C. Yesson (2010). Droseraceae Database (version 0.1, Dec 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ELPT</b><br/>L. S&ouml;derstr&ouml;m, A. Hagborg, and M. von Konrat (For a full list of contributors and collaborators see: http://www.early-land-plants-today.org/Home/participants-and-collaborators) (2010). ELPT: Early Land Plants Today - Uniting Taxonomy, Nomenclature &amp; Geography (liverworts and hornworts) (version 1.0, Nov 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ETI WBD (Euphausiacea)</b><br/>E. Brinton, M.D. Ohman, A.W. Townsend, M.D. Knight &amp; A.L. Bridgeman (eds of Euphausiacea) (2010). ETI WBD: World Biodiversity Database (Euphausiacea) (version 2.1, Nov 2002). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>FishBase</b><br/>R. Froese &amp; D. Pauly (eds) (2010). FishBase (version Jan 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>FLOW</b><br/>T. Bourgoin (2010). FLOW: Fulgoromorpha Lists On the WEB (version 8, Sep 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>FWCrabs</b><br/>C. Magalh&atilde;es (2010). FWCrabs: Neotropical Freshwater Crabs Catalogue (version Oct 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>GCC</b><br/>C. Flann (ed) (2010). GCC: Global Compositae Checklist (version 1 (Beta), Nov 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>GloBIS (GART)</b><br/>C. H&auml;user, J. Holstein &amp; A. Steiner (eds) (2010). GloBIS (GART): Global Butterfly Information System (version 0.2, Nov 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Glomeromycota</b><br/>A. Sch&uuml;&szlig;ler &amp; C. Walker (2010). Glomeromycota (version 8.0, Sep 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Hexacorals</b><br/>D.G. Fautin (2010). Hexacorals: Hexacorallians of the World (version Jul 2001). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ICTV_MSL</b><br/>M.J. Adams, L.A. Ball, C. B&uuml;chen-Osmond, E.B. Carstens, P. Christian, A.J. Davison, U. Desselberger, C.M. Fauquet, A.E. Gorbalenya, A.L. Haenni, A.M.Q. King, N.J. Knowles, P.J. Krell, R. Lavigne, E.J. Lefkowitz, D.J. McGeoch, J. Mackenzie, I.J. Molineux, K. Nagasaki, D. Prangishvili, H. Sanfacon, H.S. Savithri, S. Siddell, C. Suttle, J.L. Van Etten, H.J. Vetten (2010). ICTV/MSL: International Committee on Taxonomy of Viruses / Master Species List (version Apr 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ILDIS</b><br/>Y.R. Roskov, F.A. Bisby, J.L. Zarucchi, B.D. Schrire &amp; R.J. White (eds) (2010). ILDIS World Database of Legumes (version 10.01, May 2007). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>IOPI-GPC</b><br/>K.L. Wilson and W.G. Berendsohn (eds) (2010). IOPI Global Plant Checklist (version 10.0, Aug 2007). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ITIS</b><br/>T. Orrell (custodian) (2010). ITIS: The Integrated Taxonomic Information System (version Sep 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ITIS Bees</b><br/>T. Orrell (custodian) (2010). ITIS Bees: World Bee Checklist (version Sep 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>LDL Neuropterida</b><br/>J.D. Oswald (2010). LDL Neuropterida Species of the World (version Sep 2007). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>LecyPages</b><br/>S.A. Mori, G.T. Prance &amp; M. Tulig (2010). LecyPages: The Lecythidaceae Pages (version Oct 2006). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>LepIndex</b><br/>G.W. Beccaloni, M.J. Scoble, G.S. Robinson &amp; B. Pitkin (2010). LepIndex: The Global Lepidoptera Names Index (version 12.2, Jun 2005). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>LHD</b><br/>F.E. Young (2010). LHD: Lacistemataceae Holistic Database (version Oct 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>LIAS</b><br/>G. Rambold (lead editor); for detailed information see http://liaslight.lias.net/About/Impressum.html and http://liasnames.lias.net/About/Impressum.html (2010). LIAS: A Global Information System for Lichenized and Non-Lichenized Ascomycetes (version Jul 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>MBB</b><br/>D. Burckhardt (2010). MBB: Moss Bug Base (version 1.0, Sep 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>MOST</b><br/>M.R. Crosby (ed) (2010). MOST: Moss TROPICOS Database (version 1, Jul 2004). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>MSF</b><br/>D. Otte &amp; M. Stiewe (2010). MSF: Mantodea Species File Online (version 1.0/4.0, Apr 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Nomen.eumycetozoa.com</b><br/>C. Lado &amp; J.C. Hern&aacute;ndez-Crespo (2010). Nomen.eumycetozoa.com (version Oct 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>NZIB</b><br/>D. Gordon (ed) (2010). NZIB: New Zealand Inventory of Biodiversity (version Jun 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Odonata</b><br/>J. van Tol (2010). Odonata: Catalogue of the Odonata of the World (version 1.3, Aug 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>OlogamasidBase</b><br/>R.C. Castilho, E.S. Silva &amp; G.J. de Moraes (2010). Mites GSDs: OlogamasidBase (version Oct 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>OSF</b><br/>D.C. Eades &amp; D. Otte (2010). OSF: Orthoptera Species File Online (version 2.0/4.0, Apr 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Parhost</b><br/>S. Medvedev, A. Lobanov &amp; I. Lyangouzov (2010). Parhost: World Database of Fleas (version 2, Nov 2005). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Phyllachorales</b><br/>P.F. Cannon (2010). Phyllachorales (version 8.0, Sep 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>PhytoseiidBase</b><br/>R.C. Castilho, J.P.Z. Narita, G.J. de Moraes &amp; J.A. McMurtry (2010). Mites GSDs: PhytoseiidBase (version Sep 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>PlecopteraSF</b><br/>R.E. DeWalt; U. New-Becker &amp; G. Stueber (2010). PlecopteraSF: Plecoptera Species File Online (version 1.1/4.0, Apr 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>PSF</b><br/>P. Brock (2010). PSF: Phasmida Species File (version 2.1/4.0, Apr 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Psyllist</b><br/>D. Ouvrard (2010). Psyl'list: Psylloidea database (version 2.0, Oct 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>RhodacaridBase</b><br/>R.C. Castilho &amp; G.J. de Moraes (2010). Mites GSDs: RhodacaridBase (version Oct 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Rhytismatales</b><br/>D.W. Minter (2010). Rhytismatales (version 8.0. Sep 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>RJB Geranium</b><br/>C. Aedo (2010). RJB Geranium: Geranium Taxonomic Information System (version May 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Rotifera</b><br/>H. Segers (2010). Rotifera Database (version Oct 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>SalticidDB</b><br/>J. Pr&oacute;szynski (2010). SalticidDB: Global Species Database of Salticidae (Araneae) (version 23 Aug 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ScaleNet</b><br/>Y. Ben-Dov &amp; D.R. Miller (2010). ScaleNet: Systematic Database of the Scale Insects of the World (version Dec 2004). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Scarabs</b><br/>P. Schoolmeesters (2010). Scarabs: World Scarabaeidae Database (version Jul 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Solanaceae Source</b><br/>S. Knapp, L. Walley, L. Bohs, M. Nee &amp; D. Spooner (eds) (2010). Solanaceae Source (version 200811, Nov 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Species 2000 Common Names</b><br/>R. Froese (2010). Species 2000 additional Common Names for the Catalogue of Life (version Jan 2006). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Species Fungorum</b><br/>P.M. Kirk (2010). Species Fungorum (version 8.0. Sep 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>SpidCat</b><br/>N.I. Platnick &amp; R.J. Raven (2010). SpidCat: The World Spider Catalog (version 8.5, Jan 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>SysMyr</b><br/>J. Spelda (2010). SysMyr: Systematic Myriapod Database (version Dec 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Taxapad Ichneumonoidea</b><br/>D.S.K. Yu (2010). Taxapad Ichneumonoidea (version May 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>TenuipalpidBase</b><br/>N.C. Mesa, R. Ochoa, W.C. Welbourn, G.A. Evans, R.C. Castilho &amp; G.J. de Moraes (2010). Mites GSDs: TenuipalpidBase (version Nov 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>TicksBase</b><br/>A.M. Nijhof, A.A. Guglielmone &amp; I.G. Horak (2010). TicksBase (version 5.6, Jun 2005). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>TIGR Reptiles</b><br/>P. Uetz (2010). TIGR Reptile Database (version Oct 2007). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Tineidae NHM</b><br/>G.S. Robinson (2010). Tineidae NHM: Global Taxonomic Database of Tineidae (Lepidoptera) (version 8.0, Jun 2007). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>TITAN</b><br/>G. Tavakilian (2010). TITAN: Cerambycidae database (version May 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Trichomycetes</b><br/>R.W. Lichtwardt (2010). Trichomycetes (version 8.0, Sep 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>UCD</b><br/>J. Noyes (2010). UCD: Universal Chalcidoidea Database (version Sep 2007). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>URMO</b><br/>J. van der Land (ed) (2010). URMO: UNESCO-IOC Register of Marine Organisms (version Nov 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>World Checklist of Selected Plant Families</b><br/>R. Govaerts (ed). See <a href="http://apps.kew.org/wcsp/compilersReviewers.do">http://apps.kew.org/wcsp/compilersReviewers.do</a>
for the list of reviewers. (2010). World Checklist of Selected Plant Families (version 27 Nov 2009). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>World Gracillariidae</b><br/>J. De Prins &amp; W. De Prins (2010). World Gracillariidae: Global Taxonomic Database of Gracillariidae (version March 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>WoRMS Brachiopoda &amp; Phoronida</b><br/>C.C. Emig (2010). WoRMS Brachiopoda &amp; Phoronida: Brachiopoda &amp; Phoronida World Databases (version Oct 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>WoRMS Bryozoa</b><br/>P. Bock &amp; D. Gordon
(2010). WoRMS Bryozoa: World Marine Bryozoa Database (version Aug 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>WoRMS Cumacea</b><br/>L. Watling (2010). WoRMS Cumacea: Cumacea World Database (version Oct 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>WoRMS Ophiuroidea</b><br/>S. St&ouml;hr &amp; T. O'Hara (2010). WoRMS Ophiuroidea: World Ophiuroidea Database (version Oct 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>WoRMS Porifera</b><br/>R. van Soest (ed) (2010). WoRMS Porifera: World Porifera Database (version Oct 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>WoRMS Proseriata &amp; Kalyptorhynchia</b><br/>T. Artois &amp; E. Schockaert (2010). WoRMS Proseriata and Kalyptorhynchia: World database of Proseriata &amp; Kalyptorhynchia (version Oct 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>WTaxa</b><br/>M.A. Alonso-Zarazaga &amp; C.H.C. Lyal (authors), M. S&aacute;nchez-Ruiz (technical editor) (2010). WTaxa: Electronic Catalogue of Weevil names (Curculionoidea) (version May 2010). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Xylariaceae</b><br/>Y.M. Ju &amp; J. Rogers (2010). Xylariaceae: Home of the Xylariaceae (version 8.0, Sep 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>ZOBODAT (Vespoidea)</b><br/>J. Gusenleitner (2010). ZOBODAT: Zoological-Botanical Database (Vespoidea) (version 5.0, Jul 2006). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

<p><b>Zygomycetes</b><br/>P.M. Kirk (2010). Zygomycetes (version 8.0, Sep 2008). In: Species 2000 &amp;
ITIS Catalogue of Life, 2nd October 2010 (Bisby F.A., Roskov Y.R., Orrell T.M.,
Nicolson D., Paglinawan L.E., Bailly N., Kirk P.M., Bourgoin T., Baillargeon G.,
Ouvrard D., eds). Digital resource at http://www.catalogueoflife.org/col. Species 2000: Reading, UK.</p>

</div>
<?php
echo $this->navigator_bottom;
?>