<?php
/**
 * Annual Checklist Interface
 *
 * contact.phtml
 * Info - Contact page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<h1 class="page_header">
<?php echo $this->translate('Contact_us')?>
</h1>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>This is the fourteenth edition of the Annual Checklist. Users are
encouraged to provide feedback to the Species 2000 Secretariat and to
ITIS. Enquiries about the Annual Checklist, the databases or Species
2000 should also be directed to:</p>
<p>CoL Secretariat <br />
Species 2000 <br />
Naturalis Biodiversity Center <br />
Darwinweg 4, 2333 CL Leiden, Netherlands <br />
</p>
<p>Email: <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a><br />
Tel: +31 71 751 7363 <br />
</p>
<p>Help Desk: <a href="mailto:support@sp2000.org">
support@sp2000.org</a></p>

<p class="field_header">Annual Checklist DVD requests</p>
<p>The Annual Checklist database and software on the DVD are identical to
those on the web at <a href="http://www.catalogueoflife.org/annual-checklist/2013" target="_blank">
http://www.catalogueoflife.org/annual-checklist</a>.
Further copies of the DVD (or the 2015 edition that will be released in
March-April 2015) can be requested free of charge from the Species 2000
website (<a href="http://www.sp2000.org/cdrequest" target="_blank">http://www.sp2000.org/cdrequest</a>)
or by emailing <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a>.
</p>

</div>
<?php
echo $this->navigator_bottom; ?>