<div class="page_header">
<?php echo $this->translate('Contact_us') ?>
</div>
<br/>

<div align=center>
    <input type='button' name='goPrev' class='formbutton' value='<< Previous' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/websites'">
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <select name='select_page' onchange='document.location.href=this.options[this.selectedIndex].value'>
        <option value='<?php echo $this->baseUrl(); ?>/info/about'>About the Catalogue of Life</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/ac'>About the 2009 Annual Checklist</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/databases'>Source databases</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/hierarchy'>Towards Management Hierarchy</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/copyright'>Copyrights, reproduction & sale</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/cite'>How to cite this work</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/websites'>Web sites</option>
        <option selected value='<?php echo $this->baseUrl(); ?>/info/contact'>Contact us</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/acknowledgements'>Acknowledgements</option>
    </select>
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <input type='button' name='goNext' class='formbutton' value=' Next >> ' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/acknowledgements'">
</div>
<br />

<p>This is the 


ninth

 edition of the Annual Checklist. 
                            Users are encouraged to provide feedback to the Species 
                            2000 Secretariat and to ITIS. Enquiries about this 
                            Annual Checklist, the databases or Species 2000 should 
                            also be directed to: </p>
                          <p>Species 2000 Secretariat <br>
                            


Harborne Building<br>
                            The University of Reading <br>
                            Reading RG6 6AS, UK <br>
                          </p>

                          <p>Email:  <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a><br>
                            Tel: +44 118 378 6466 <br>
                          </p>
                          <p>CD-ROM Help Desk: 


                          <a href="mailto:support@sp2000.org"> support@sp2000.org</a></p>
                          <p><strong> Annual Checklist CD requests </strong></p>

                          <p> The Annual Checklist database and software on the CD are identical to those on the web at <a href="http://www.catalogueoflife.org/annual-checklist/2009/">www.catalogueoflife.org/annual-checklist/2009/</a>. Further copies of this CD (or the 2010 edition that will be released in April 2010) can be requested free of charge from the Species 2000 website (<a href="http://www.sp2000.org/cdrequest/">www.sp2000.org/cdrequest/</a>) or by emailing <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a>. </p>
                          <p>In addition to supplying a single free copy of the Annual Checklist to those who request it, it is our policy to supply up to 20 extra copies to those willing to distribute copies to a group or network of institutions in developing countries. If you are requesting more than one copy please supply a brief explanation and list of institutes to which they will be distributed.
                          </p>

<div class="horizontal_line"><br /></div><br />
<div align=center>
    <input type='button' name='goPrev' class='formbutton' value='<< Previous' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/websites'">
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <select name='select_page' onchange='document.location.href=this.options[this.selectedIndex].value'>
        <option value='<?php echo $this->baseUrl(); ?>/info/about'>About the Catalogue of Life</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/ac'>About the 2009 Annual Checklist</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/databases'>Source databases</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/hierarchy'>Towards Management Hierarchy</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/copyright'>Copyrights, reproduction & sale</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/cite'>How to cite this work</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/websites'>Web sites</option>
        <option selected value='<?php echo $this->baseUrl(); ?>/info/contact'>Contact us</option>
        <option value='<?php echo $this->baseUrl(); ?>/info/acknowledgements'>Acknowledgements</option>
    </select>
    <img src='images/blank.gif' width='8' height='1' border='0'>
    <input type='button' name='goNext' class='formbutton' value=' Next >> ' onClick="JavaScript: document.location.href='<?php echo $this->baseUrl(); ?>/info/acknowledgements'">
</div>