<?php
/**
 * Annual Checklist Interface
 *
 * contact.phtml
 * Info - Contact page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Contact_us')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>This is the tenth edition of the Annual Checklist. Users are
encouraged to provide feedback to the Species 2000 Secretariat and to
ITIS. Enquiries about this Annual Checklist, the databases or Species
2000 should also be directed to:</p>
<p>Species 2000 Secretariat <br />
Harborne Building<br />
The University of Reading <br />
Reading RG6 6AS, UK <br />
</p>
<p>Email: <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a><br />
Tel: +44 118 378 6466 <br />
</p>
<p>DVD Help Desk: <a href="mailto:support@sp2000.org">
support@sp2000.org</a></p>
<p><strong> Annual Checklist DVD requests </strong></p>
<p>The Annual Checklist database and software on the DVD are identical to
those on the web at <a href="<?php echo $this->app->location; ?>">
<?php echo $this->app->location; ?></a>.
Further copies of this DVD (or the 2011 edition that will be released in
April 2011) can be requested free of charge from the Species 2000
website (<a href="http://www.sp2000.org/cdrequest">http://www.sp2000.org/cdrequest</a>)
or by emailing <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a>.
</p>
<p>In addition to supplying a single free copy of the Annual Checklist
to those who request it, it is our policy to supply up to 20 extra
copies to those willing to distribute copies to a group or network of
institutions in developing countries. If you are requesting more than
one copy please supply a brief explanation and list of institutes to
which they will be distributed.</p>
<p>
We also encourage our users to download DVD ISO image from www.sp2000.org and
make own copy of the disk.
</p>
</div>
<?php
echo $this->navigator_bottom; ?>