<?php
/**
 * Annual Checklist Interface
 *
 * copyright.phtml
 * Info - Copyright page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Copyright_reproduction_sale')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>&copy; 2010, Species 2000<br />
This online database is copyrighted by Species 2000 on behalf of the
Catalogue of Life partners.</p>
<p>Use of the content (such as the classification, synonymic species
checklist, and scientific names) for publications and databases by
individuals and organisations for not-for-profit usage is encouraged, on
condition that full and precise credit is given at three levels on all
occasions that records are shown. The three part credit the complete
work, the contributing database of the record, and the expert who
provides taxonomic scrutiny of the individual record. For example, these
might be as follows:</p>
<p>1) <i>Species 2000 &amp; ITIS Catalogue of Life: <?php echo $this->app->edition; ?>
 Annual Checklist</i>,<br />
2) The full or short name of the contributing database, such as:
<em>Early Land Plants Today - Uniting Taxonomy</em>, <em>Nomenclature &amp;
 Geography (liverworts and hornworts)</em> or <em>ELPT</em>,<br />
3) When provided, the latest taxonomic scrutiny field (specialist name
&amp; date), such as <em>Proszynski J., 01-Oct-2009</em> (from
 <em>Global Species Database of Salticidae</em>), <em>Flann C., 16-Aug-09</em>
 (from <em>Global Compositae Checklist</em>) or <em>Warwick S.I., Francis A.
 &amp; Al-Shehbaz I.A., 2009</em> (from <em>Brassicaceae species checklist
 and database</em>).<br />
</p>
<p>This three-part credit can in many cases be kept brief by using a
standard form and one or more logos as in the following example:
"Species recognized by M Guiry, AlgaeBase in <img
    src="<?php echo $this->baseUrl(); ?>/images/CoL_logo.png"
    alt="CoL_logo" width="95" border="0" height="17">". You may copy the
Catalogue of Life logo from this example, on the DVD and web versions,
for use in giving credit.</p>
<p>If you wish to use the content on a public portal or webpage you are
required to notify the Species 2000 Secretariat, both to request written
permission and to assist with a check that the correct credits are
given.</p>
<p><b> Commercial Use </b></p>
<p>Use of this compilation or any of the databases contained within it by
 commercial organisations requires a written agreement from Species 2000 and ITIS.
 This applied when it is used commercially for external services, products or
 publications and when it is used to provide internal services within an organisation.
</p>
<p><b> Disclaimer </b></p>
<p><b></b>The Species 2000 &amp; ITIS Catalogue of Life editorial board
cannot guarantee the accuracy or completeness of the information in this
Annual Checklist. Be aware that the Catalogue of Life is still
incomplete and undoubtedly contains errors. Neither Species 2000 &amp;
ITIS nor any of the <?php echo $this->stats['databases']; ?> contributing
databases can be made liable for any direct or indirect damage arising out of
the use of Catalogue of Life.</p>

<p>Copyright for booklet photographs remains with the contributors.</p>
<p>ISSN 1473-009X</p>
</div>
<?php
echo $this->navigator_bottom;
?>