<?php
/**
 * Annual Checklist Interface
 *
 * databases.phtml
 * Info - Source databases page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Source_databases'), '"' . $this->key . '"')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>The data in the 2012 Annual Checklist have
been provided by <?php #echo $this->stats['databases']; ?>115 databases. 
Of these 14 are new to this edition and 44 have been updated over the past year (three databases have been updated twice during the annual cycle). 
Most datasets include one or more global
species database sectors (GSDs), i.e. datasets being developed to cover
all of the world's species in a particular group of organisms. A few
datasets provide regional information for groups not yet covered
globally. The datasets result from collaboration and editing by many
expert taxonomists, whose names are found in the datasets themselves. A
brief summary is listed below giving: database short and full names;
home page on the web; the author(s) or editor(s); organisation; the
group for which data are provided, preceded by its higher
classification; and the number of species and infraspecific taxa
included in this checklist.</p>
<p><i>Dataset Qualifiers</i><br />
In this edition of the Catalogue of Life we introduce &quot;Dataset Qualifiers&quot; which shown in the interface. Qualifiers give users a quick guide to the reliability of presented data. Qualifiers have been given by authors/editors of each database and appear on the Database Details page, and alongside, with the database name on each Species Details page. Qualifiers reflect data reliability in the Catalogue of Life only, and are not applicable to the original view of the database throught its own website. Qualifiers include:
<div style="margin-left: 10px;">
&#8226; Geographical Coverage (values G for &quot;Global&quot; and R for &quot;Regional&quot;)<br />
&#8226; Dataset Completeness (values 1 - 100%)<br />
&#8226; Checklist Confidence (values <img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'>&#8212;<img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'>, see below for details)
</div>
<div style="margin-left: 30px;"><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'>  Caution! This data set does not contain a scrutinised taxonomic checklist, and in parts may be a list of names only. However, as the only available resource at the time, it was included in the Catalogue of Life to fill temporarily a major gap. See database abstract for more details.<br /> 
<img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'>  Caution! This data set is a scrutinised taxonomic checklist, but is incomplete and at an early stage of its development. See database abstract for more details. <br />
<img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'>This is a well scrutinised taxonomic checklist but is restricted to a subset of species by geography, or sector of biological discipline (conservation, medical and molecular oriented systems, etc). This data set was included in the Catalogue of Life to fill temporarily gaps at lower levels of the taxonomic classification (e.g. species, genera). See database abstract for more details.<br />
<img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'>  This is a nearly complete and fully scrutinised taxonomic checklist with a good quality of expertise at the current stage of its development.<br />
<img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'><img src='<?php echo $this->baseUrl(); ?>/images/star.png' style='height:10px; width:11;'>  This is a complete and fully scrutinised taxonomic checklist for an entire taxon with a high quality of expertise and frequent updates, which covers nearly all known species diversity in the taxon worldwide. 
</div>
</p>

<br />
<table>
<?php
$rowClass = "odd";
?>
    <tr class="even">
        <th class="horizontal<?php echo ($this->sort == 'source' ? ' current' : '');?>">
            <a href="<?php echo $this->url(array_merge($this->urlParams, array(
              'sort' => 'source', 'direction' => $this->sortDesc == 'source' ? 'desc' : 'asc'))); ?>">
              <?php echo $this->translate('Source_database'); ?></a>
            <span class="sort-arrow"><?php echo ($this->sort == 'source' ? $this->sortArrow : '');?></span>
        </th>
        <th class="horizontal"></th>
        <th class="horizontal<?php echo ($this->sort == 'group' ? ' current' : '');?>">
            <a href="<?php echo $this->url(array_merge($this->urlParams, array(
              'sort' => 'group', 'direction' => $this->sortDesc == 'group' ? 'desc' : 'asc'))); ?>">
              <?php echo $this->translate('English_name_of_the_group'); ?></a>
            <span class="sort-arrow"><?php echo ($this->sort == 'group' ? $this->sortArrow : '');?></span>
        </th>
        <th class="horizontal<?php echo ($this->sort == 'names' ? ' current' : '');?>">
            <a href="<?php echo $this->url(array_merge($this->urlParams, array(
              'sort' => 'names', 'direction' => $this->sortDesc == 'names' ? 'desc' : 'asc'))); ?>">
              <?php echo $this->translate('Species'); ?></a>
            <span class="sort-arrow"><?php echo ($this->sort == 'names' ? $this->sortArrow : '');?></span>
        </th>
    </tr>
<?php foreach ($this->results as $items) : ?>

    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical">
            <a href="<?php echo $this->baseUrl() . $items['url']; ?>">
                <?php echo $items['name']; ?>
            </a>
            <?php if (!empty($items['is_new'])) : ?>
                <span class="new_big"><?php echo $items['is_new']; ?></span>
            <?php endif; ?>
        </th>
        <td>
        <?php if ($items['label']) : ?>
            <a class="wrapLogo tinyImgLink"
                href="<?php  echo $this->baseUrl() . $items['url']; ?>">
                <img src="<?php echo $this->baseUrl() . $items['thumb']; ?>"
                     alt="<?php echo $items['label']; ?>"
                     title="<?php echo $items['label']; ?>" />
            </a>
        <?php endif; ?>
        </td>
        <td><?php echo $items['taxa']; ?></td>
        <td class="number"><?php echo $items['accepted_species_names']; ?></td>
    </tr>
    <?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <?php endforeach; ?>
</table>
</div>
<?php echo $this->navigator_bottom; ?>