<?php
/**
 * Annual Checklist Interface
 *
 * databases.phtml
 * Info - Source databases page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Source_databases'), '"' . $this->key . '"')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>The data in the <i><b>The Catalogue of Life, 2nd October 2010</b></i> have
been provided by 80<?php /*echo $this->stats['databases']; */?> databases. Of these 4 have been
updated since 1st July 2010. Most datasets include one or more global
species database sectors (GSDs), i.e. datasets being developed to cover
all of the world's species in a particular group of organisms. A few
datasets provide regional information for groups not yet covered
globally. The datasets result from collaboration and editing by many
expert taxonomists, whose names are found in the datasets themselves. A
brief summary is listed below giving: database short and full names;
home page on the web; the author(s) or editor(s); organisation; the
group for which data are provided, preceded by its higher
classification; and the number of species and infraspecific taxa
included in this checklist.</p>
<br />
<table>
<?php
$rowClass = "odd";
?>
    <tr class="even">
        <th class="horizontal<?php echo ($this->sort == 'source' ? ' current' : '');?>">
            <a href="<?php echo $this->url(array_merge($this->urlParams, array(
              'sort' => 'source', 'direction' => $this->sortDesc == 'source' ? 'desc' : 'asc'))); ?>">
              <?php echo $this->translate('Source_database'); ?></a>
            <span class="sort-arrow"><?php echo ($this->sort == 'source' ? $this->sortArrow : '');?></span>
        </th>
        <th class="horizontal"></th>
        <th class="horizontal<?php echo ($this->sort == 'group' ? ' current' : '');?>">
            <a href="<?php echo $this->url(array_merge($this->urlParams, array(
              'sort' => 'group', 'direction' => $this->sortDesc == 'group' ? 'desc' : 'asc'))); ?>">
              <?php echo $this->translate('English_name_of_the_group'); ?></a>
            <span class="sort-arrow"><?php echo ($this->sort == 'group' ? $this->sortArrow : '');?></span>
        </th>
        <th class="horizontal<?php echo ($this->sort == 'names' ? ' current' : '');?>">
            <a href="<?php echo $this->url(array_merge($this->urlParams, array(
              'sort' => 'names', 'direction' => $this->sortDesc == 'names' ? 'desc' : 'asc'))); ?>">
              <?php echo $this->translate('Species'); ?></a>
            <span class="sort-arrow"><?php echo ($this->sort == 'names' ? $this->sortArrow : '');?></span>
        </th>
    </tr>

<?php foreach ($this->results as $items) : ?>

    <tr class="<?php echo $rowClass; ?>">
        <th class="vertical">
            <a href="<?php echo $this->baseUrl() . $items['url']; ?>">
                <?php echo $items['name']; ?>
            </a>
            <?php if ($items['is_new'] == 1) : ?>
                <span class="new_big"><?php echo $this->translate('NEW')?></span>
            <?php endif; ?>
        </th>
        <td>
        <?php if ($items['label']) : ?>
            <a class="wrapLogo tinyImgLink"
                href="<?php  echo $this->baseUrl() . $items['url']; ?>">
                <img src="<?php echo $this->baseUrl() . $items['thumb']; ?>"
                     alt="<?php echo $items['label']; ?>"
                     title="<?php echo $items['label']; ?>" />
            </a>
        <?php endif; ?>
        </td>
        <td><?php echo $items['taxa']; ?></td>
        <td class="number"><?php echo $items['accepted_species_names']; ?></td>
    </tr>
    <?php $rowClass = ($rowClass == 'odd' ? 'even' : 'odd'); ?>
    <?php endforeach; ?>
</table>
</div>
<?php echo $this->navigator_bottom; ?>