<?php
/**
 * Annual Checklist Interface
 *
 * estimates.phtml
 * Info - Species estimates view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php echo $this->translate('Species_estimates') ?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>Explanation of this table.<br/><br/></p>
<table>
<?php // print_r($this->results) ?>
<?php $first = true; ?>
<?php foreach ($this->results['phyla'] as $kingdom => $phyla): ?>
    <?php $first ? $padding = '' : $padding = 'padded'; ?>
    <tr class="<?php echo $padding; ?>">
        <th><?php echo $kingdom; ?></th>
        <th><?php echo $this->translate('Estimated_numer_of_species'); ?></th>
        <th><?php echo $this->translate('Actual_number_of_species'); ?></th>
        <th><?php echo $this->translate('Coverage'); ?></th>
    </tr>
    <?php $rowClass = "even" ?>
    <?php foreach ($phyla as $phylum): ?>
    <?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <td><?php echo $phylum['name'] ?></td>
        <td><?php echo $phylum['estimate'] ?></td>
        <td><?php echo $phylum['actual'] ?></td>
        <td><?php echo $phylum['coverage'] ?></td>
    </tr>
    <?php endforeach; ?>
    <?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="<?php echo $rowClass; ?>">
        <td><?php echo $this->translate('Total_coverage'); ?></td>
        <td></td>
        <td></td>
        <td><?php echo $this->results['totals'][$kingdom]; ?></td>
    </tr>
    <?php $first = false; ?>
<?php endforeach ?>
</table>
</div>
<?php
echo $this->navigator_bottom; ?>