<?php
/**
 * Annual Checklist Interface
 *
 * about.phtml
 * Info - Special 2010 Edition
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Info_special_edition'), $this->app->edition);
?>
</div>
<?php echo $this->navigator_top;?>
<div class="info_content">

 
<p class="iyb-slogan">In the Catalogue of Life, 2020-06-02 Beta</p>

<p class="field_header">There is a new taxonomic checklist:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Collembola.org: Checklist of the Collembola of the World by Frans Janssens, P.F. Bellinger & K.A. Christiansen</p>
</div>
<p>&nbsp;</p>
 
<p class="field_header">Two databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; FLOW. <i>Database was updated through recovery of automated pipe to the CoL+ Clearinghouse.</i></p>
<p>&#8226; Scarabs (<i>third update in a year cycle</i>). <i>Database data have been imported via CoLDP format.</i></p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Taxa of higher ranks, missing in previous releases, are returned in the Tree.</p>
<p>&#8226; Additional fixes are applied in Species Fungorum Plus and Nomen.eumycetozoa.com references.</p>
</div>
<p>&nbsp;</p>
 
<p class="field_header">Known, but unfixed issues in Beta version:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Some species estimates might be missing in the Tree.</p>
<p>&#8226; Some authorstrings in species names might be incorrectly interpreted by the parser.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>
 
 
<p class="iyb-slogan">In the Catalogue of Life, 2020-04-16 Beta</p>

<p class="field_header">Two databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Species Fungorum Plus. <i>The new version of the database brings together previously independent GSDs such as Dothideomycetes, Glomeromycota, Phyllachorales, Rhytismatales, Saccharomycetes, Species Fungorum, Xylariaceae & Zygomycetes. It also temporarily replaces lichenized fungi previously covered by LIAS. Species Fungorum Plus contributes taxonomically unplaced names from Index Fungorum to CoL+.</i></p>
<p>&#8226; Nomen.eumycetozoa.com</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Known, but unfixed issues in Beta version:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Some taxa of higher ranks with no species are missing.</p>
<p>&#8226; Some species estimates might be missing in the Tree.</p>
<p>&#8226; Some authorstrings in species names might be incorrectly interpreted by the parser.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>
 
 
 
<p class="iyb-slogan">In the Catalogue of Life, 2020-02-24 Beta</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Sepidiini tribe: World catalogue of the tribe Sepidiini (Tenebrionidae, Coleoptera) by Marcin Kamiński with colleagues</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Two databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Scarabs <i>(second update in a year cycle)</i> </p>
<p>&#8226; WSC: World Spider Catalog </p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Classification down to genus rank in Chromista, Protozoa and in all algae phyla have been updated with IRMNG: Interim Register of Marine and Nonmarine Genera of March 2019.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>
 
 

<p class="iyb-slogan">In this release of the Catalogue of Life<br><span style="font-weight:normal">(2020-01-10 Beta)</span></p>
<div style='margin-left: 10px;'>
<p>
Between May and December 2019, the Catalogue of Life migrated in a new software environment developed by CoL+ GBIF project with the participation of Olaf Banki as a PI, Markus Döring and Ayco Holleman as back-end developers, and Thomas Jeppesen as a front-end developer.
</p>
<p>
We are presenting a first pilot release of the CoL database which was generated in a new environment. It includes data from 166 GSDs almost identical to the 2019 Annual Checklist. Four regional and thematic checklists, which temporarily filled taxonomic gaps in the CoL, have been removed from the global checklist: ITIS Regional, Catalogue of Life China, New Zealand Inventory of Biodiversity and some taxa from The Paleobiology Database. These checklists will appear in a regional component of the CoL.
</p>
<p>
Only World Scarabaeidae Database has been updated for a new version in this pilot release.
</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the 2019 Annual Checklist<br><span style="font-weight:normal">(21st April 2019)</span></p>
<div style='margin-left: 10px;'>
<p>
2019 Annual Checklist contained contributions from 172 taxonomic databases with information on 1,837,565 living and 63,418 extinct species, 160,909 living and 590 extinct infraspecific taxa which belong to 184,526 genera, 12,267 families, 1,643 orders, 387 classes, 104 phyla and 7 kingdoms plus viruses, it also included 1,710,092 synonyms and 437,994 common names. More information is available at <a href= "http://www.catalogueoflife.org/annual-checklist/2019/info/ac" target="_blank">www.catalogueoflife.org/annual-checklist/2019</a>.
</p>
</div>
<p>&nbsp;</p>
 
</div>

<?php
echo $this->navigator_bottom;
?>
