<?php
/**
 * Annual Checklist Interface
 *
 * about.phtml
 * Info - Special 2010 Edition
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Info_special_edition'), $this->app->edition);
?>
</div>

<?php
echo $this->navigator_top;
?>

<div class="info_content">

<p class="iyb-slogan">In the 2011 Annual Checklist</p>
<p class="field_header">There are 22 new taxonomic databases:</p>
<div style='margin-left: 10px;'> 
<p>&#8226; 3i Cicadellinae by D. Takiya & D. Dmitriev,</p>
<p>&#8226; 3i Typhlocybinae by D. Dmitriev,</p>
<p>&#8226; CunaxidBase by J. den Heyer,</p>
<p>&#8226; Dothideomycetes by P.W. Crous,</p>
<p>&#8226; Embioptera Species File Online (ESF) by M. Maehr,</p>
<p>&#8226; LIAS, a Global Information System for Lichenized and Non-Lichenized Ascomycetes by G. Rambold as the lead editor (LIAS database replaces the lichen taxa previously provided by Species Fungorum),</p>
<p>&#8226; Membracoidea of the World Database (MOWD) by S. McKamey,</p>
<p>&#8226; Saccharomycetes by L.C. Offord & P.M. Kirk,</p>
<p>&#8226; Spider Mites Web (SpmWeb) by A. Migeon & F. Dorkeld,</p>
<p>&#8226; WoRMS Asteroidea by C.L. Mah,</p>
<p>&#8226; WoRMS Bochusacea by G.A. Boxshall,</p>
<p>&#8226; WoRMS Brachypoda by G.A. Boxshall,</p>
<p>&#8226; WoRMS Bryozoa by P. Bock & D. Gordon (WoRMS Bryozoa replaces the bryozoan taxa previously provided by ITIS),</p>
<p>&#8226; WoRMS Isopoda by M. Schotte, C.B. Boyko, N.L. Bruce, G.C.B. Poore, S. Taiti, G.D.F. Wilson (eds),</p>
<p>&#8226; WoRMS Mystacocarida by G.A. Boxshall,</p>
<p>&#8226; WoRMS Nemertea by J.L. Norenburg,</p>
<p>&#8226; WoRMS Polychaeta by G. Read & K. Fauchald,</p>
<p>&#8226; WoRMS Remipedia by S. Koenemann, M. Hoenemann & T. Stemme (eds),</p>
<p>&#8226; WoRMS Tantulocarida (families Basipodellidae, Deoterthridae, Doryphallophoridae, Microdajidae) by G.A. Boxshall,</p>
<p>&#8226; WoRMS Thermosbaenacea by G. Poore,</p>
<p>&#8226; WoRMS World List of Marine Oligochaeta by T. Timm,</p>
<p>&#8226; WoRMS Xenoturbellida by S. Gofas</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Replacement:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Systema Dipterorum replaced the former Biosystematic Database of World Diptera (BDWD)</p>
</div>

<p>&nbsp;</p>
<p class="field_header">22 taxonomic databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Aphid Species File,</p>
<p>&#8226; Blattodea Species File,</p>
<p>&#8226; Conifer Database,</p>
<p>&#8226; FishBase,</p>
<p>&#8226; Global Compositae Checklist,</p>
<p>&#8226; Global Taxonomic Database of Gracillariidae,</p>
<p>&#8226; Glomeromycota,</p>
<p>&#8226; Home of Xylariaceae,</p>
<p>&#8226; Lacistemataceae Holistic Database,</p>
<p>&#8226; Mantodea Species File,</p>
<p>&#8226; Orthoptera Species File,</p>
<p>&#8226; Phasmida Species File,</p>
<p>&#8226; Phyllachorales,</p>
<p>&#8226; Plecoptera Species File,</p>
<p>&#8226; Rhytismatales,</p>
<p>&#8226; SalticidDB,</p>
<p>&#8226; Species Fungorum,</p>
<p>&#8226; Trichomycetes,</p>
<p>&#8226; World Checklist of Selected Plant Families (WCSP),</p>
<p>&#8226; World Scarabaeidae Database,</p>
<p>&#8226; Wtaxa,</p>
<p>&#8226; Zygomycetes,</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Updates in ITIS sectors:</p>
<p>
<div style='margin-left: 10px;'> 
<p>&#8226; ITIS phylum Sipuncula replaces data previously provided by URMO.
</div>

Following ITIS sectors have also updated:
<div style='margin-left: 10px;'> 
<p>&#8226; Animalia - Arthropoda - Maxillopoda - Calanoida - family Aetideidae (World checklist)</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - family Sphaeriusidae</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - Cucujoidea - family Corylophidae (N. American checklist)</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - Tenebrionoidea - families Mycetophagidae & Tetratomidae (N. American checklists)</p>
<p>&#8226; Animalia - Chordata - Mammalia - Carnivora - Canidae - species Vulpes vulpes</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Changes in the management classification:</p>

<div style='margin-left: 10px;'>
<p>&#8226; Fungi classification has been changed, and it is now compatible with the 10th edition of the Dictionary of the Fungi (Kirk, Cannon, Minter & Stalper, 2008 - CABI)</p>
<p>&#8226; The hierarchy of the Animalia phyla has changed following recommendations from a panel of experts led by M. Ruggiero, D. Gordon and N. Bailly, with technical assistance from D. Nicolson.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Additional data has been contributed:</p>

<div style='margin-left: 10px;'>
<p>&#8226; Aljos Farjon (Conifer Database) contributed over 4,000 new Conifer common names in 20 languages as a result of his 4D4Life pilot project.</p>
<p>&#8226; Paul Schoolmeesters (Scarabs database) contributed 11,720 new species from the family Melolonthidae as a result of his 4D4Life pilot project.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Other improvements:</p>

<div style='margin-left: 10px;'>
<p>ILDIS common names records have been atomized by names, languages and countries of usage.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">New content feature:</p>

<div style='margin-left: 10px;'> 
<p>A full list of citations for the contributing databases, using the recommended style, 
is now available from the how to cite page at 
<a href = "http://www.catalogueoflife.org/col/info/cite">www.catalogueoflife.org/col/info/cite</a>.
 These may be used for copying & pasting such citations.
</p>
</div>
</div>
<?php
echo $this->navigator_bottom;
?>
