<?php
/**
 * Annual Checklist Interface
 *
 * about.phtml
 * Info - Special 2010 Edition
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Info_special_edition'), $this->app->edition);
?>
</div>
<?php
echo $this->navigator_top
?>
<div class="info_content">

<p class="iyb-slogan">In this 3rd January 2011 version</p>
<p class="field_header">There are 15 new taxonomic databases:</p>
<div style='margin-left: 10px;'> 
<p>&#8226; 3i Cicadellinae by D. Takiya & D. Dmitriev</p>
<p>&#8226; 3i Typhlocybinae by D. Dmitriev</p>
<p>&#8226; Embioptera Species File Online (ESF) by M. Maehr</p>
<p>&#8226; Membracoidea of the World Database (MOWD) by S. McKamey</p>
<p>&#8226; Spider Mites Web (SpmWeb) by A. Migeon & F. Dorkeld</p>
<p>&#8226; WoRMS Asteroidea by C.L. Mah</p>
<p>&#8226; WoRMS Bochusacea by G.A. Boxshall</p>
<p>&#8226; WoRMS Brachypoda by G.A. Boxshall</p>
<p>&#8226; WoRMS Isopoda by M. Schotte, C.B. Boyko, N.L. Bruce, G.C.B. Poore, S. Taiti, G.D.F. Wilson (eds)</p>
<p>&#8226; WoRMS Mystacocarida by G.A. Boxshall</p>
<p>&#8226; WoRMS Nemertea by J.L. Norenburg</p>
<p>&#8226; WoRMS Polychaeta by G. Read & K. Fauchald</p>
<p>&#8226; WoRMS Remipedia by S. Koenemann, M. Hoenemann & T. Stemme (eds)</p>
<p>&#8226; WoRMS Tantulocarida (families Basipodellidae, Deoterthridae, Doryphallophoridae, Microdajidae) by G.A. Boxshall</p>
<p>&#8226; WoRMS Thermosbaenacea by G. Poore</p>
</div>
<p>&nbsp;</p>
<p class="field_header">Updates in ITIS sectors:</p>
<p>
<div style='margin-left: 10px;'> 
<p>&#8226; ITIS phylum Sipuncula replaces data previously provided by URMO.
</div>

Following ITIS sectors have also updated:

<div style='margin-left: 10px;'> 
<p>&#8226; Animalia - Arthropoda - Maxillopoda - Calanoida - family Aetideidae (World checklist)</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - family Sphaeriusidae</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - Cucujoidea - family Corylophidae (N. American checklist)</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - Tenebrionoidea - families Mycetophagidae & Tetratomidae (N. American checklists)</p>
<p>&#8226; Animalia - Chordata - Mammalia - Carnivora - Canidae - species Vulpes vulpes</p>
</div>
<p>&nbsp;</p>
<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>ILDIS common names records have been atomized by names, languages and countries of usage.</p>
</div>
<p>&nbsp;</p>
<hr/>
<p>&nbsp;</p>
<p class="iyb-slogan">In the Catalogue of Life, 2nd October 2010</p>

<p class="field_header">There are three new taxonomic databases:</p>

<p>
<div style='margin-left: 10px;'> 
<p>&#8226; CunaxidBase: Family Cunaxidae Database by J. den Heyer.</p>
<p>&#8226; LIAS: A Global Information System for Lichenized and Non-Lichenized Ascomycetes by G. Rambold as the lead editor (LIAS database replaces the lichen taxa previously provided by Species Fungorum).</p>
<p>&#8226; WoRMS Bryozoa: World Marine Bryozoa Database by P. Bock & D. Gordon (WoRMS Bryozoa replaces the bryozoan taxa previously provided by ITIS).</p> 
</div>
</p>
<p>&nbsp;</p>
<p class="field_header">Four taxonomic databases have been updated:</p>

<p>
<div style='margin-left: 10px;'> 
<p>&#8226; Lacistemataceae Holistic Database</p>
<p>&#8226; SalticidDB</p>
<p>&#8226; World Scarabaeidae Database</p>
<p>&#8226; WTaxa</p>
</div>
</p>
<p>&nbsp;</p>
<p class="field_header">Additional data has been contributed:</p>

<p>
<div style='margin-left: 10px;'> 
<p>&#8226; Aljos Farjon (Conifer Database) contributed over 4,000 new Conifer common names in 20 languages as a result of his 4D4Life pilot project.</p>
<p>&#8226; Paul Schoolmeesters (Scarabs database) contributed 11,720 new species from the family Melolonthidae as a result of his 4D4Life pilot project.</p>
</div>
<p>&nbsp;</p>
</p>
<p class="field_header">New feature:</p>
<p>A full list of citations for the contributing databases, using the recommended style, is now available from the <a href ='www.catalogueoflife.org/col/info/cite'>how to cite</a> page at <a href ='www.catalogueoflife.org/col/info/cite'>www.catalogueoflife.org/col/info/cite</a>. These may be used for copying & pasting such citations.</p>

<br />
<hr />
<p>&nbsp;</p>
<p class="iyb-slogan">In the Catalogue of Life, 1st July 2010</p>


<p class="field_header">Eight taxonomic databases have been updated:</p>

<p>
<div style='margin-left: 10px;'> 
<p>&#8226; Aphid Species File,</p>
<p>&#8226; Blattodea Species File,</p>
<p>&#8226; Conifer Database,</p> 
<p>&#8226; Global Taxonomic Database of Gracillariidae,</p>
<p>&#8226; Orthoptera Species File,</p> 
<p>&#8226; Phasmida Species File,</p> 
<p>&#8226; Plecoptera Species File,</p> 
<p>&#8226; Mantodea Species File</p> 
</div>
</p>

<p>&nbsp;</p>
<p class="field_header">The following bugs have been fixed:</p>
<div style='margin-left: 10px;margin-right: 100px'>
<p>&#8226; Missing order names in some ITIS sectors returned back.</p>
<p>&#8226; 175 ITIS family names have been misplaced in superfamily field in AC10. Corrected in this version.</p> 
<p>&#8226; 52,654 empty infraspecific marker values caused the problem with species and infraspecific taxa statistics in AC10. Problem fixed in this version.</p> 
<p>&#8226; 33,017 missing common names have been returned back to the database.</p>
<p>&#8226; Position of the family Poaceae in the classification have been corrected.</p>
<p>&#8226; Redundant phylum name Hepatophyta has been deleted. All liverworts species are placed in the phylum Marchantiophyta.</p>
<p>&#8226; Few duplications in species authorstrings have been fixed.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Changes in the management classification:</p>
<div style='margin-left: 10px;margin-right: 100px'>
<p>&#8226; Phylum name &quot;Ectoprocta&quot; has been changed to &quot;Bryozoa&quot; in response to request from Dennis Gordon (22 July 2010)</p>
</div>

</div>
<?php
echo $this->navigator_bottom;
?>