<?php
/**
 * Annual Checklist Interface
 *
 * totals.phtml
 * Info - Species totals view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php echo $this->translate('Species_totals') ?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>This table presents a known species tally for the phyla represented in the Catalogue of Life. 
It compares the actual number of recognised species, worldwide, to the number of accepted and provisionally 
accepted names estimated for that phylum in the current literature; hover over the book icon 
to display the source used for the estimate. The last column displays the completeness 
(or coverage) of the Catalogue of Life, expressed as a percentage.</p>
<table id="species-totals">
<?php $first = true; ?>
<?php foreach ($this->results['phyla'] as $kingdom => $phyla): ?>
    <?php $first ? $padding = '' : $padding = 'padded'; ?>
    <tr class="<?php echo $padding; ?>">
        <th>Taxon</th>
        <th class="number">Actual number in CoL</th>
        <th class="number">Estimated number</th>
        <th></th>
        <th class="number">CoL completeness</th>
    </tr>
     <tr>
        <td></td>
        <td class="no-padding">(Recognised species, worldwide)</td>
        <td class="no-padding">(Accepted & provisionally accepted species)</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td colspan="5" class="field_header"><?php echo $kingdom; ?></td>
    </tr>
    <?php $rowClass = "even" ?>
    <?php foreach ($phyla as $phylum): ?>
    <?php $rowClass = ($rowClass == "odd" ? "even" : "odd"); ?>
    <tr class="<?php echo $rowClass; ?>">
        <td><?php echo $phylum['name'] ?></td>
        <td class="number"><?php echo $phylum['actual'] ?></td>
        <td class="number"><?php echo $phylum['estimate'] ?></td>
        <td class="icon"><?php echo $phylum['source']; ?></td>
        <td class="number"><?php echo $phylum['coverage'] ?></td>
    </tr>
    <?php endforeach; ?>
    <?php $rowClass = ($rowClass == "odd" ? "even" : "odd");?>
    <tr class="tally">
        <td>Known species tally</td>
        <td class="number"><?php echo $this->results['totals'][$kingdom]['actual']; ?></td>
        <td class="number"><?php echo $this->results['totals'][$kingdom]['estimate']; ?></td>
        <td></td>
        <td class="number"><?php echo $this->results['totals'][$kingdom]['coverage']; ?></td>
    </tr>
    <?php $first = false; ?>
<?php endforeach ?>
</table>
</div>
<?php
echo $this->navigator_bottom; ?>