<div class="page_header">
<?php echo $this->translate('Web_sites') ?>
</div>
<?php echo $this->navigator_top; ?>
<br/>
<br/>

<p><b><?php echo $this->translate('Online_version_of_the_Annual_Checklist'); ?>:</b>
</p>

<p><a href="http://www.catalogueoflife.org/annual-checklist/2009/" target="_blank">www.catalogueoflife.org/annual-checklist/2009/</a>
</p>

<p><strong><?php echo $this->translate('Web_service'); ?></strong>
</p>

<p><?php echo $this->placeholder($this->translate('Species_2000_provides_web_services_to_facilitate_automated_access_to')); ?></p>

<div class="horizontal_line"><br /></div><br />
<?php echo $this->navigator_bottom; ?>