<?php
/**
 * Annual Checklist Interface
 *
 * websites.phtml
 * Info - Websites page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Web_sites')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p><b>Online version of the Annual Checklist:</b></p>
<p><a href="<?php echo $this->app->location; ?>" target="_blank"><?php echo $this->app->location; ?></a></p>
<p><b>Web service</b></p>
<p>Species 2000 provides web services to facilitate automated access to
the Annual Checklist by computer programs. Please visit
<a href="http://www.sp2000.org/webservices">http://www.sp2000.org/webservices</a> for
more information.</p>
</div>
<?php
echo $this->navigator_bottom;
?>