<div class="page_header">
<?php
echo $this->translate('Web_sites')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p><b>Online version of the Annual Checklist:</b></p>
<p><a href="http://www.catalogueoflife.org/annual-checklist/2009/"
    target="_blank">www.catalogueoflife.org/annual-checklist/2009/</a></p>
<p><b>Web service</b></p>
<p>Species 2000 provides web services to facilitate automated access to
the Annual Checklist by computer programs. Please visit
<a href="http://www.sp2000.org/webservices">www.sp2000.org/webservices</a> for
more information.</p>
</div>
<div class="horizontal_line"><br />
</div>
<?php
echo $this->navigator_bottom;
?>