<?php
/**
 * Annual Checklist Interface
 *
 * error.phtml
 * Error template
 *
 * @category    ACI
 * @package     application
 * @subpackage  views
 *
 */
?>
<?php if ('development' != APPLICATION_ENV): ?>
<div class="page_header">
<?php echo $this->translate('An_error_occured') ?>
</div>
<br/>

<p><?php echo $this->translate('Error_notice') ?></p>
<br/>
<p><?php echo $this->translate('Error_reported') ?></p>
<br/>

<?php elseif ('development' == APPLICATION_ENV): ?>

<?php echo $this->doctype();?>
<html>
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
</head>
<body>
  <h1><?php echo $this->translate('An_error_occured'); ?></h1>
  <h2><?php echo $this->translate('Application_error'); ?></h2>
      
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage(); ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString(); ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php var_dump($this->request->getParams()); ?>
  </pre>
  <?php else: ?>
  <p><?php echo $this->exception->getMessage(); ?></p>
</body>
</html>
<?php endif; ?>