<?php
/**
 * Annual Checklist Interface
 *
 * export.phtml
 * Export page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php echo $this->translate('Export_search_results'); ?>
</div>
<br/>
<p><?php echo sprintf(
    $this->translate('Click_the_button_below_to_export'),
    $this->encoding
); ?></p>
<br/>
<p><?php echo $this->translate('The_exported_data'); ?></p>
<br/>
<div class="copyright_notice">
<p class="page_title"><?php echo $this->translate('Copyright_notice'); ?></p>
<p><?php echo $this->translate('Copyright_notice_text'); ?></p>
</div>
<div class="export-form">
<?php echo $this->form; ?>
</div>
<div class="export-warning">
<?php echo sprintf(
    $this->translate(sprintf('Export_warning')),
    number_format($this->export_limit)
); ?>
</div>
<br/>
<br/>
<div class="page_links align-left">
<a href="javascript:history.back()">
    <?php echo '<< ' . $this->translate('Back_to_search_results'); ?>
</a>
</div>