<?php
/**
 * Annual Checklist Interface
 *
 * form.phtml
 * Form view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php echo $this->formHeader; ?>
</div>
<div id="form-box">
<?php if ($this->form->isErrors()): ?>
    <div class="errors">
        <ul>
            <li><?php echo $this->form->getErrorMessage(); ?></li>
        </ul>
    </div>
<?php endif; ?>
<div class="form-container">
<form id="clear_form" name="clear_form" action="<?php echo $this->baseUrl($this->controller.'/'.$this->action); ?>" method="post"><input type="hidden" name="reset" value="1" /></form>
<?php 
if($this->mapSearchModuleEnabled == true && $this->controller == 'search' && $this->action == 'distribution'): ?>
<form id="searchFormWithMap" action="<?php echo $this->baseUrl($this->controller.'/'.$this->action); ?>" onsubmit="submitSearchForm" method="post" enctype="application/x-www-form-urlencoded">
<div id="region_search">
	<div id="regions"><select name="regionList" id="regionSelectList" multiple="multiple"></select></div>
	<input type="hidden" name="regions" id="selectedRegions" value="" />
	<div id="map_canvas"></div>
	<div id="region_standards">
	<?php echo $this->translate('Choose_layer');?>:<br />
		<input type="radio" name="regionStandard" value="1" onclick="javascript:getRegionsInRegionSelect(1);" CHECKED /> <?php echo $this->translate('TDWG_Regions_Level_4');?><br />
		<input type="radio" name="regionStandard" value="2" onclick="javascript:getRegionsInRegionSelect(2);" /> <?php echo $this->translate('IHO_Sea_Areas');?><br />
		<input type="radio" name="regionStandard" value="3" onclick="javascript:getRegionsInRegionSelect(3);" /> <?php echo $this->translate('World_Exclusive_Economic_Zones');?><br />
		<input type="radio" name="regionStandard" value="4" onclick="javascript:getRegionsInRegionSelect(4);" /> <?php echo $this->translate('TDWG_Continents_Level_1');?>
	</div>
</div>
<!-- <div class="search-form">
<dd id="submitGroup-element">
<fieldset id="fieldset-submitGroup">
<dl>
<dt id="clear-label">&nbsp;</dt>
<dd id="clear-element">
<span class="dijit dijitReset dijitLeft dijitInline dijitButton" dojoattachevent="ondijitclick:_onButtonClick,onmouseenter:_onMouse,onmouseleave:_onMouse,onmousedown:_onMouse" widgetid="clear">
<span class="dijitReset dijitRight dijitInline">
<span class="dijitReset dijitInline dijitButtonNode">
<button id="clear" class="dijitReset dijitStretch dijitButtonContents" waistate="labelledby-clear_label" wairole="button" value="" type="button" name="clear" dojoattachpoint="titleNode,focusNode" role="button" aria-labelledby="clear_label" tabindex="0" style="-moz-user-select: none;">
</span>
</span>
</span>
</dd>
<dt id="search-label">&nbsp;</dt>
<dd id="search-element">
<span class="dijit dijitReset dijitLeft dijitInline dijitButton" dojoattachevent="ondijitclick:_onButtonClick,onmouseenter:_onMouse,onmouseleave:_onMouse,onmousedown:_onMouse" widgetid="search">
<span class="dijitReset dijitRight dijitInline">
<span class="dijitReset dijitInline dijitButtonNode">
<button id="search" class="dijitReset dijitStretch dijitButtonContents" waistate="labelledby-search_label" wairole="button" value="Search" type="submit" name="search" dojoattachpoint="titleNode,focusNode" role="button" aria-labelledby="search_label" tabindex="0" style="-moz-user-select: none;">
</span>
</span>
</span>
</dd>
</dl>
</fieldset>
</dd>
</div> -->
<input type="submit" value="<?php echo $this->translate('Search');?>" name="search">
<button onclick="javascript:clearDistributionSearchForm();" waistate="labelledby-clear_label" wairole="button" value="" type="button" name="clear" dojoattachpoint="titleNode,focusNode" class="dijitReset dijitStretch dijitButtonContents" role="button" aria-labelledby="clear_label" id="clear" tabindex="0" style="-moz-user-select: none;"><span dojoattachpoint="iconNode" class="dijitReset dijitInline"><span class="dijitReset dijitToggleButtonIconChar">&nbsp;</span></span><span dojoattachpoint="containerNode" id="clear_label" class="dijitReset dijitInline dijitButtonText"><?php echo $this->translate('Clear_form');?></span></button>
</form>
<?php else:
	echo $this->form;
endif; ?>
</div>
</div>