<?php
/**
 * Annual Checklist Interface
 *
 * form.phtml
 * Form view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php echo $this->formHeader; ?>
</div>
<div id="form-box">
<?php if ($this->form->isErrors()): ?>
    <div class="errors">
        <ul>
            <li><?php echo $this->form->getErrorMessage(); ?></li>
        </ul>
    </div>
<?php endif; ?>
<div class="form-container">
<?php echo $this->form; ?>
</div>
</div>