<div class="formheader"><?php echo $this->t->translate('Search_the_Annual_Checklist'); ?></div>
<div class="divider"></div>

<?php echo $this->form; ?>

<!--
<form action="" method="post">
<table>
    <tr>
        <td><p>Search for:</p></td>
        <td><input type="text" name="search" value="" /></td>
    </tr>
    <tr>
        <td></td>
        <td><p><input type="checkbox" name="wholewordsonly" /> Match whole words
            only</p></td>
    </tr>
    <tr>
        <td colspan="2" align="right"><input type="submit" value="Search >>" />
            </td>
    </tr>
</table>
</form>
-->
<?php echo $this->t->translate('Number_Of_Records_Found'); ?>: <?php echo $this->numResults; ?>