<?php
/**
 * Annual Checklist Interface
 *
 * data.phtml
 * Export template for search all data
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<?php
$language = str_replace('"','',$this->data['author']);
echo $this->data['name'] .
	 (str_replace('"','',$this->data['status']) == 'common name' && $language != '' ? ' (' . $language . ')' : '') . $this->separator . 
     $this->data['rank'] . $this->separator .
     $this->data['status'] . $this->separator .
     $this->data['accepted_species_name'] . $this->separator .
     $this->data['kingdom'] . $this->separator .
     $this->data['db_name'] . PHP_EOL;
unset($this->data);