<p class="form_header"><?php echo $this->translate('Browse_taxonomic_tree'); ?></p>
<?php
echo '<script type="text/javascript">';
echo 'var baseUrl = "' . $this->baseUrl() . '";';
echo 'var hierarchy = new Array(' . $this->hierarchy . ');';
echo '</script>';
?>
<script type="text/javascript">
init = function() {
    var store = new dojox.data.QueryReadStore({ url: baseUrl + '/browse/tree/fetch/taxa' });
    var model = new ACI.dojo.QueryStoreModel({
        store: store,
        query: { id: 0 },
        id: 'tree',
        labelAttr: 'name',
        rootLabel: '',
        typeAttr:'type',
        childrenAttr: 'children'
    }, 'store');
    var tree = new ACI.dojo.TxTree({ model: model }, 'tree');
    tree.persist = false;

    if(hierarchy.length > 1) {
        var handler = dojo.connect(tree, 'onOpen', null, function(item, node) {
            dojo.forEach(node.getChildren(),function(cNode) {
                var pos = dojo.indexOf(hierarchy, cNode.item.i.id);
                if(pos >= 0) {
                    tree.focusNode(cNode);
                    if(pos == hierarchy.length - 1) {
                        dijit.scrollIntoView(cNode.domNode);
                        dojo.disconnect(handler);
                    }
                    else {
                        tree._expandNode(cNode);
                    }
                    return;
                }
            });
        });
    }
}
dojo.addOnLoad(init);
</script>
<div id="tree"></div>