<?php
/**
 * Annual Checklist Interface
 *
 * tree.phtml
 * Browse tree view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<h1 class="page_header"><?php echo $this->translate('Browse_taxonomic_tree'); ?></h1>

<script type="text/javascript">
var showCommentFeedback = <?php echo ($this->feedbackModuleEnabled ? 1 : 0) ?>;
var hierarchy = new Array(<?php echo $this->hierarchy; ?>);
var jsFeedbackUrl = "<?php echo $this->jsFeedbackUrl; ?>";
var treeHash = "<?php echo $this->hash; ?>";
<?php echo $this->jsTranslation; ?>
</script>

<?php if($this->statisticsModuleEnabled || $this->iconsInTreeModuleEnabled || $this->fossilsInTreeModuleEnabled): ?>
<div id="tree-checkboxes">
<?php if($this->statisticsModuleEnabled): ?>
    <input <?php if($this->showEstimationCheckboxSelected != false) echo 'checked'; ?> id="showStatisticsCheckbox" type="checkbox" name="showEstimates" value="0" onclick="showOrHide('treeStatistics')" />
    <label for="showStatisticsCheckbox"><?php echo $this->textShowStatistics; ?></label>
    <input <?php if($this->showSourceDatabaseCheckboxSelected != false) echo 'checked'; ?> id="showGSDCheckbox" type="checkbox" name="showGSD" value="0" onclick="showOrHide('treeSourceDatabase')" />
    <label for="showGSDCheckbox"><?php echo $this->textShowSourceDatabases; ?></label>
<?php endif; ?>
<?php if($this->iconsInTreeModuleEnabled): ?>
    <input <?php if($this->showIconsInTreeSelected != false) echo 'checked'; ?> id="showIconsCheckbox" type="checkbox" name="showIcons" value="0" onclick="showOrHide('iconSpan')" />
    <label for="showIconsCheckbox"><?php echo $this->textShowIcons; ?></label>
<?php endif; ?>
<?php if($this->fossilsModuleEnabled): ?>
    <input <?php if($this->showExtinctInTreeSelected == 1) echo 'checked'; ?> id="showExtinctCheckbox" type="checkbox" name="showExtinct" value="0" onclick="showOrHideExtinct()" />
    <label for="showExtinctCheckbox"><?php echo $this->textShowExtinct; ?></label>
<?php endif; ?>
</div>
<?php endif; ?>
<script type="text/javascript">
dojo.require("dijit.TooltipDialog");
var dialog;

initTree = function() {
    var store = new dojox.data.QueryReadStore({ url: baseUrl + '/browse/tree/fetch/taxa' });
    var model = new ACI.dojo.TxStoreModel({
        store: store,
        query: { id: 0 },
        id: 'tree',
        labelAttr: 'name',
        rootLabel: '',
        typeAttr:'type',
        childrenAttr: 'children'
    }, 'store');
    var tree = new ACI.dojo.TxTree({ model: model }, 'tree');
    tree.persist = false;
};

initInfoPanel = function() {
    dialog = new dijit.TooltipDialog({
    	"class": "infoPanel"
    });
};

dojo.addOnLoad(initTree);
dojo.addOnLoad(initInfoPanel);
</script>
<div id="tree"></div>